DROP PROCEDURE Insert IF EXISTS;
DROP PROCEDURE Select IF EXISTS;
DROP TABLE HELLOWORLD IF EXISTS;

CREATE TABLE HELLOWORLD (
   HELLO VARCHAR(15),
   WORLD VARCHAR(15),
   DIALECT VARCHAR(15) NOT NULL,
   PRIMARY KEY (DIALECT)
);
-- PARTITION TABLE HELLOWORLD ON COLUMN DIALECT;

CREATE PROCEDURE Insert AS INSERT INTO HELLOWORLD (Hello, World, Dialect) VALUES (?, ?, ?);
CREATE PROCEDURE Select AS SELECT HELLO, WORLD FROM HELLOWORLD WHERE DIALECT = ?;
