CREATE TABLE P1 (
    ID INTEGER NOT NULL,
    INT INTEGER,
    VCHAR_INLINE VARCHAR(14)
);
PARTITION TABLE P1 ON COLUMN ID;

CREATE TABLE R1 (
    ID INTEGER NOT NULL,
    INT INTEGER,
    VCHAR_INLINE VARCHAR(42 BYTES)
);
