-- replicated table, pure column index
CREATE TABLE T (
    C1 INTEGER NOT NULL,
    C2 INTEGER NOT NULL,
    C3 INTEGER NOT NULL,
    C4 INTEGER NOT NULL
);
CREATE INDEX T_IDX1_TREE ON T(C1);
CREATE INDEX T_IDX2_TREE ON T(C1, C2);
CREATE INDEX T_IDX3_TREE ON T(C2, C1);
CREATE INDEX T_IDX4_TREE ON T(C1, C2, C3);

-- replicated table, expression index (mixed case too)
CREATE TABLE ET (
    C1 INTEGER NOT NULL,
    C2 INTEGER NOT NULL,
    C3 INTEGER NOT NULL,
    C4 INTEGER NOT NULL
);
CREATE INDEX ET_IDX1_TREE ON ET(C1 + C2);
CREATE INDEX ET_IDX2_TREE ON ET(ABS(C3 - 49));
CREATE INDEX ET_IDX3_TREE ON ET(C1 - C2, C2 - C3);
CREATE INDEX ET_IDX4_TREE ON ET(C1, C2 * C3);
CREATE INDEX ET_IDX5_TREE ON ET(C1 + C2, C3);

-- partitioned table, partiton column is indexable
CREATE TABLE P1 (
    C1 INTEGER NOT NULL,
    C2 INTEGER NOT NULL,
    C3 INTEGER NOT NULL,
    C4 INTEGER NOT NULL
);
PARTITION TABLE P1 ON COLUMN C1;
CREATE INDEX P1_IDX1_TREE ON P1(C1);
CREATE INDEX P1_IDX2_TREE ON P1(C1, C2);
CREATE INDEX P1_IDX3_TREE ON P1(C2, C1);
CREATE INDEX P1_IDX4_TREE ON P1(C1, C2, C3);

-- partitioned table, partiton column is not indexable
CREATE TABLE P2 (
    C1 INTEGER NOT NULL,
    C2 INTEGER NOT NULL,
    C3 INTEGER NOT NULL,
    C4 INTEGER NOT NULL
);

PARTITION TABLE P2 ON COLUMN C4;
CREATE INDEX P2_IDX1_TREE ON P2(C1);
CREATE INDEX P2_IDX2_TREE ON P2(C1, C2);
CREATE INDEX P2_IDX3_TREE ON P2(C2, C1);
CREATE INDEX P2_IDX4_TREE ON P2(C1, C2, C3);
