CREATE TABLE P1 (
	A INTEGER NOT NULL,
	C INTEGER NOT NULL,
	D INTEGER NOT NULL
);
PARTITION TABLE P1 ON COLUMN A;
CREATE TABLE P2 (
	A INTEGER NOT NULL,
	C INTEGER NOT NULL,
	D INTEGER NOT NULL
);
PARTITION TABLE P2 ON COLUMN A;


CREATE TABLE R1 (
	A INTEGER NOT NULL,
	C INTEGER NOT NULL
);
CREATE TABLE R2 (
	A INTEGER NOT NULL,
	C INTEGER NOT NULL
);

