DROP TABLE AAA IF EXISTS;
DROP TABLE BBB IF EXISTS;
DROP TABLE AAA_PA IF EXISTS;
DROP TABLE AAA_PB IF EXISTS;
DROP TABLE AAA_PC IF EXISTS;

CREATE TABLE AAA (
    A INTEGER,
    B INTEGER,
    C INTEGER,
);

CREATE TABLE BBB (
    A INTEGER,
    B INTEGER,
    C INTEGER,
);

CREATE TABLE AAA_PA (
    A INTEGER NOT NULL,
    B INTEGER NOT NULL,
    C INTEGER NOT NULL,
);
PARTITION TABLE AAA_PA ON COLUMN A;

CREATE TABLE AAA_PB (
    A INTEGER NOT NULL,
    B INTEGER NOT NULL,
    C INTEGER NOT NULL,
);
PARTITION TABLE AAA_PB ON COLUMN B;

CREATE TABLE AAA_PC (
    A INTEGER NOT NULL,
    B INTEGER NOT NULL,
    C INTEGER NOT NULL,
);
PARTITION TABLE AAA_PC ON COLUMN C;
