CREATE TABLE P (
	PARTKEY INTEGER NOT NULL,
	D1   INTEGER NOT NULL,
	D2   INTEGER NOT NULL,
	D3   INTEGER NOT NULL,
	VAL1 INTEGER NOT NULL,
	VAL2 INTEGER NOT NULL,
	VAL3 INTEGER NOT NULL,
);

PARTITION TABLE P ON COLUMN PARTKEY;

CREATE TABLE R (
	D1   INTEGER NOT NULL,
	D2   INTEGER NOT NULL,
	D3   INTEGER NOT NULL,
	VAL1 INTEGER NOT NULL,
	VAL2 INTEGER NOT NULL,
	VAL3 INTEGER NOT NULL,
);

CREATE VIEW VP (V_D1, V_D2, V_D3, V_PARTKEY, CNT, SUM_V1, SUM_V2, SUM_V3)
    AS SELECT D1, D2, D3, PARTKEY, COUNT(*), SUM(VAL1), SUM(VAL2), SUM(VAL3)
    FROM P
    GROUP BY D1, D2, D3, PARTKEY;

CREATE INDEX ENG4826_VP_COUNT ON VP(CNT);

CREATE INDEX ENG4826_VP_ALT_ORDER ON VP(V_D3, V_D2, V_D1);

CREATE VIEW VPF (V_D1, V_D2, V_PARTKEY, V_D3, CNT, SUM_V1, SUM_V2, SUM_V3)
    AS SELECT D1, D2, PARTKEY, D3, COUNT(*), SUM(VAL1), SUM(VAL2), SUM(VAL3)
    FROM P
    GROUP BY D1, D2, PARTKEY, D3;

CREATE VIEW VNP (V_D1, V_D2, V_D3, CNT, SUM_V1, SUM_V2, SUM_V3)
    AS SELECT D1, D2, D3, COUNT(*), SUM(VAL1), SUM(VAL2), SUM(VAL3)
    FROM P
    GROUP BY D1, D2, D3;

CREATE VIEW VR (V_D1, V_D2, V_D3, CNT, SUM_V1, SUM_V2, SUM_V3)
    AS SELECT D1, D2, D3, COUNT(*), SUM(VAL1), SUM(VAL2), SUM(VAL3)
    FROM R
    GROUP BY D1, D2, D3;

CREATE INDEX ENG4826_VR_COUNT ON VR(CNT);

CREATE INDEX ENG4826_VR_ALT_ORDER ON VR(V_D3, V_D2, V_D1);

CREATE VIEW VPM (V_D1, V_D2, V_D3, CNT, MIN_VAL1, MAX_VAL2, SUM_VAL3)
    AS SELECT D1, D2, D3, COUNT(*), MIN(VAL1), MAX(VAL2), SUM(VAL3)
    FROM P
    GROUP BY D1, D2, D3;

CREATE VIEW VRM (V_D1, V_D2, V_D3, CNT, MIN_VAL1, MAX_VAL2, SUM_VAL3)
    AS SELECT D1, D2, D3, COUNT(*), MIN(VAL1), MAX(VAL2), SUM(VAL3)
    FROM R
    GROUP BY D1, D2, D3;

