CREATE TABLE T (
	T_D0   INTEGER NOT NULL,
	T_D1   INTEGER NOT NULL,
	T_D2   INTEGER NOT NULL,
	CONSTRAINT T_TREE PRIMARY KEY (T_D0, T_D1)
);

CREATE TABLE T2 (
    T_D0 INTEGER NOT NULL,
    T_D1 INTEGER NOT NULL,
    T_D2 INTEGER NOT NULL,
    CONSTRAINT T2_TREE PRIMARY KEY (T_D0, T_D1)
);

CREATE TABLE T3 (
    T_D0 INTEGER NOT NULL,
    T_D1 INTEGER NOT NULL,
    T_D2 INTEGER NOT NULL
);

CREATE INDEX T3_PARTIAL_IDX on T3 (T_D1) WHERE T_D2 > 3;
CREATE INDEX T3_IDX on T3 (T_D0);

CREATE TABLE P (
    P_D0 INTEGER NOT NULL,
    P_D1 INTEGER NOT NULL,
    P_D2 INTEGER NOT NULL,
);

CREATE INDEX P_D1_IDX ON P (P_D1);
PARTITION TABLE P ON COLUMN P_D0;

CREATE TABLE Tnokey (
	T_D0   INTEGER NOT NULL,
	T_D1   INTEGER NOT NULL,
	T_D2   INTEGER NOT NULL,
);

CREATE TABLE Tnokey2 (
    T_D0 INTEGER NOT NULL,
    T_D1 INTEGER NOT NULL,
    T_D2 INTEGER NOT NULL
);

CREATE TABLE Tmanykeys (
	T_D0   INTEGER NOT NULL,
	T_D1   INTEGER NOT NULL,
	T_D2   INTEGER NOT NULL,
	CONSTRAINT T_TREE_3 PRIMARY KEY (T_D0, T_D1, T_D2)
);

