CREATE TABLE T1 (
	A INTEGER NOT NULL
);

CREATE TABLE T2 (
	B INTEGER NOT NULL
);

CREATE TABLE T3 (
	C INTEGER NOT NULL
);

CREATE TABLE T4 (
	D INTEGER NOT NULL
);

CREATE TABLE T5 (
	E INTEGER NOT NULL
);

CREATE TABLE T6 (
	F INTEGER NOT NULL
);

CREATE TABLE T7 (
	G INTEGER NOT NULL
);

-- For now, these are plannertester fodder (vs. junit).
CREATE TABLE I1 (
	A INTEGER NOT NULL
    , CONSTRAINT pkeyA PRIMARY KEY(A)
);

CREATE TABLE I2 (
	B INTEGER NOT NULL
    , CONSTRAINT pkeyB PRIMARY KEY(B)
);

CREATE TABLE I3 (
	C INTEGER NOT NULL
    , CONSTRAINT pkeyC PRIMARY KEY(C)
);

CREATE TABLE I4 (
	D INTEGER NOT NULL
    , CONSTRAINT pkeyD PRIMARY KEY(D)
);

CREATE TABLE I5 (
	E INTEGER NOT NULL
    , CONSTRAINT pkeyE PRIMARY KEY(E)
);

CREATE TABLE I6 (
	F INTEGER NOT NULL
    , CONSTRAINT pkeyF PRIMARY KEY(F)
);

CREATE TABLE I7 (
	G INTEGER NOT NULL
    , CONSTRAINT pkeyG PRIMARY KEY(G)
);
