CREATE TABLE T (
	T_D0   INTEGER NOT NULL,
	T_D1   INTEGER NOT NULL,
	T_D2   INTEGER NOT NULL,
	CONSTRAINT T_TREE PRIMARY KEY (T_D0, T_D1)
);

CREATE TABLE T2 (
    T_D0 INTEGER NOT NULL,
    T_D1 INTEGER NOT NULL,
    T_D2 INTEGER NOT NULL,
    CONSTRAINT T2_TREE PRIMARY KEY (T_D0, T_D1)
);

CREATE TABLE Tnokey (
	T_D0   INTEGER NOT NULL,
	T_D1   INTEGER NOT NULL,
	T_D2   INTEGER NOT NULL,
);

CREATE TABLE Tnokey2 (
    T_D0 INTEGER NOT NULL,
    T_D1 INTEGER NOT NULL,
    T_D2 INTEGER NOT NULL
);

CREATE TABLE Tmanykeys (
	T_D0   INTEGER NOT NULL,
	T_D1   INTEGER NOT NULL,
	T_D2   INTEGER NOT NULL,
	CONSTRAINT T_TREE_3 PRIMARY KEY (T_D0, T_D1, T_D2)
);

