CREATE TABLE T1 (
	A INTEGER NOT NULL
);

CREATE TABLE T2 (
	B INTEGER NOT NULL
);

CREATE TABLE T3 (
	C INTEGER NOT NULL
);

CREATE TABLE T4 (
	D INTEGER NOT NULL
);

CREATE TABLE T5 (
	E INTEGER NOT NULL
);

CREATE TABLE T6 (
	F INTEGER NOT NULL
);

CREATE TABLE T7 (
	G INTEGER NOT NULL
);

-- For now, these are plannertester fodder (vs. junit).
CREATE TABLE I1 (
	A INTEGER NOT NULL
    , CONSTRAINT ikeyA PRIMARY KEY(A)
);

CREATE TABLE I2 (
	B INTEGER NOT NULL
    , CONSTRAINT ikeyB PRIMARY KEY(B)
);

CREATE TABLE I3 (
	C INTEGER NOT NULL
    , CONSTRAINT ikeyC PRIMARY KEY(C)
);

CREATE TABLE I4 (
	D INTEGER NOT NULL
    , CONSTRAINT ikeyD PRIMARY KEY(D)
);

CREATE TABLE I5 (
	E INTEGER NOT NULL
    , CONSTRAINT ikeyE PRIMARY KEY(E)
);

CREATE TABLE I6 (
	F INTEGER NOT NULL
    , CONSTRAINT ikeyF PRIMARY KEY(F)
);

CREATE TABLE I7 (
	G INTEGER NOT NULL
    , CONSTRAINT ikeyG PRIMARY KEY(G)
);

CREATE TABLE P1 (
	A INTEGER NOT NULL
);

PARTITION TABLE P1 ON COLUMN A;

CREATE TABLE P2 (
	B INTEGER NOT NULL
);

PARTITION TABLE P2 ON COLUMN B;

CREATE TABLE P3 (
	C INTEGER NOT NULL
);

PARTITION TABLE P3 ON COLUMN C;

CREATE TABLE P4 (
	D INTEGER NOT NULL
);

PARTITION TABLE P4 ON COLUMN D;


CREATE TABLE J1 (
	A INTEGER NOT NULL
    , CONSTRAINT jkeyA PRIMARY KEY(A)
);

PARTITION TABLE J1 ON COLUMN A;

CREATE TABLE J2 (
	B INTEGER NOT NULL
    , CONSTRAINT jkeyB PRIMARY KEY(B)
);

PARTITION TABLE J2 ON COLUMN B;

CREATE TABLE J3 (
	C INTEGER NOT NULL
    , CONSTRAINT jkeyC PRIMARY KEY(C)
);

PARTITION TABLE J3 ON COLUMN C;

CREATE TABLE J4 (
	D INTEGER NOT NULL
    , CONSTRAINT jkeyD PRIMARY KEY(D)
);

PARTITION TABLE J4 ON COLUMN D;
