CREATE STREAM A PARTITION ON COLUMN A_ID EXPORT TO TARGET noop (
  A_CLIENT INTEGER NOT NULL,
  A_ID INTEGER DEFAULT '0' NOT NULL,
  A_VAL INTEGER
);

CREATE STREAM b PARTITION ON COLUMN B_ID EXPORT TO TARGET noop (
  B_CLIENT INTEGER NOT NULL,
  B_ID INTEGER DEFAULT '0' NOT NULL,
  B_VAL INTEGER
);

CREATE STREAM C PARTITION ON COLUMN C_ID (
  C_CLIENT INTEGER NOT NULL,
  C_ID INTEGER DEFAULT '0' NOT NULL,
  C_VAL INTEGER
);

CREATE STREAM d PARTITION ON COLUMN D_ID (
  D_CLIENT INTEGER NOT NULL,
  D_ID INTEGER DEFAULT '0' NOT NULL,
  D_VAL INTEGER
);

create STREAM e PARTITION ON COLUMN E_id (
  e_client integer not null,
  e_id integer default '0' not null,
  e_val integer
);

create STREAM f PARTITION ON COLUMN F_ID EXPORT TO TARGET noop (
  f_client integer not null,
  f_id integer default '0' not null,
  f_val integer
);
