#!/usr/bin/env bash

CLASSPATH="../../../obj/release/prod:../../../lib"
VOLTDB="../../../bin/voltdb"
VOLTCOMPILER="../../../bin/voltcompiler"

# remove build artifacts
function clean() {
	rm -rf obj
	rm -rf debugoutput
	rm helloworld.jar
	rm -rf voltdbroot
}

# compile the source code for procedures and the client
function srccompile() {
	mkdir -p obj
	javac -classpath $CLASSPATH -d obj *.java
}

# build an application catalog
function compile() {
    srccompile
	$VOLTCOMPILER obj project.xml helloworld.jar
}

# run the voltdb server locally
function server() {
    # if a catalog doesn't exist, build one
    if [ ! -f helloworld.jar ]; then compile; fi
    # run the server
	$VOLTDB create catalog helloworld.jar deployment deployment.xml
}

# run the client that drives the example
function client() {
    srccompile
	java -classpath obj:$CLASSPATH Client
}

# Run the target passed as the first arg on the command line
# If no first arg, run server
if [ $# -gt 1 ]; then echo "Too many arguments to script"; exit; fi
if [ $# = 1 ]; then $1; else server; fi
