CREATE TABLE HELLOWORLD (
   HELLO VARCHAR(15),
   WORLD VARCHAR(15),
   DIALECT VARCHAR(15) NOT NULL,
   PRIMARY KEY (DIALECT)
);

PARTITION TABLE HELLOWORLD ON COLUMN DIALECT;

CREATE PROCEDURE FROM CLASS Insert;
CREATE PROCEDURE FROM CLASS Select;

PARTITION PROCEDURE Insert ON TABLE Helloworld COLUMN Dialect;
PARTITION PROCEDURE Select ON TABLE Helloworld COLUMN Dialect;
