/* This file is part of VoltDB.
 * Copyright (C) 2008-2017 VoltDB Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

#include "harness.h"

#include "test_utils/UniqueEngine.hpp"

#include "execution/ExecutorVector.h"

using namespace voltdb;

class RecursiveCommonTableExpressionTest : public Test {
};

// Catalog for the following DDL:
//
// CREATE TABLE EMPLOYEES (
//     LAST_NAME VARCHAR(20) NOT NULL,
//     EMP_ID INTEGER NOT NULL,
//     MANAGER_ID INTEGER
// );

// CREATE TABLE DERIVED_EMP_PATH (
//     LAST_NAME VARCHAR(20) NOT NULL,
//     EMP_ID INTEGER NOT NULL,
//     MANAGER_ID INTEGER NOT NULL,
//     LEVEL INTEGER NOT NULL,
//     PATH VARCHAR(10000) NOT NULL
// );
const std::string catalogPayload =
    "add / clusters cluster\n"
    "set /clusters#cluster localepoch 1199145600\n"
    "set $PREV securityEnabled false\n"
    "set $PREV httpdportno -1\n"
    "set $PREV jsonapi true\n"
    "set $PREV networkpartition false\n"
    "set $PREV heartbeatTimeout 90\n"
    "set $PREV useddlschema false\n"
    "set $PREV drConsumerEnabled false\n"
    "set $PREV drProducerEnabled true\n"
    "set $PREV drRole \"master\"\n"
    "set $PREV drClusterId 0\n"
    "set $PREV drProducerPort 5555\n"
    "set $PREV drMasterHost \"\"\n"
    "set $PREV drFlushInterval 1000\n"
    "set $PREV preferredSource 0\n"
    "add /clusters#cluster databases database\n"
    "set /clusters#cluster/databases#database schema \"qgRUNDM1MjQ1NDE1NDQ1MjA1NDQxNDI0QwEMWDQ1NEQ1MDRDNEY1OTQ1NDU1MzIwMjgyARIwMTUzNTQ1RjRFNDE0RAEsJDU2NDE1MjQzNDgBCDwyODMyMzAyOTIwNEU0RjU0AQgkNTU0QzRDMkMyMAlYEDVGNDk0ARoIOTRFAXwUNDc0NTUyASpKMgAIRDQxBWwFJF46ABAyOTNCCmrPAAA0AWEQNDk1NjQBcABGEYcENTAF/QA4/t0A/t0Adt0AUkkBCEM0NQXOIVWKRwEZ6kKvAQgxMzAJAlK1ARQwMjkzQgo=\"\n"
    "set $PREV isActiveActiveDRed false\n"
    "set $PREV securityprovider \"hash\"\n"
    "add /clusters#cluster/databases#database groups administrator\n"
    "set /clusters#cluster/databases#database/groups#administrator admin true\n"
    "set $PREV defaultproc true\n"
    "set $PREV defaultprocread true\n"
    "set $PREV sql true\n"
    "set $PREV sqlread true\n"
    "set $PREV allproc true\n"
    "add /clusters#cluster/databases#database groups user\n"
    "set /clusters#cluster/databases#database/groups#user admin false\n"
    "set $PREV defaultproc true\n"
    "set $PREV defaultprocread true\n"
    "set $PREV sql true\n"
    "set $PREV sqlread true\n"
    "set $PREV allproc true\n"
    "add /clusters#cluster/databases#database tables DERIVED_EMP_PATH\n"
    "set /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH isreplicated true\n"
    "set $PREV partitioncolumn null\n"
    "set $PREV estimatedtuplecount 0\n"
    "set $PREV materializer null\n"
    "set $PREV signature \"DERIVED_EMP_PATH|viiiv\"\n"
    "set $PREV tuplelimit 2147483647\n"
    "set $PREV isDRed false\n"
    "add /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH columns EMP_ID\n"
    "set /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH/columns#EMP_ID index 1\n"
    "set $PREV type 5\n"
    "set $PREV size 4\n"
    "set $PREV nullable false\n"
    "set $PREV name \"EMP_ID\"\n"
    "set $PREV defaultvalue null\n"
    "set $PREV defaulttype 0\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n"
    "add /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH columns LAST_NAME\n"
    "set /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH/columns#LAST_NAME index 0\n"
    "set $PREV type 9\n"
    "set $PREV size 20\n"
    "set $PREV nullable false\n"
    "set $PREV name \"LAST_NAME\"\n"
    "set $PREV defaultvalue null\n"
    "set $PREV defaulttype 0\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n"
    "add /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH columns LEVEL\n"
    "set /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH/columns#LEVEL index 3\n"
    "set $PREV type 5\n"
    "set $PREV size 4\n"
    "set $PREV nullable false\n"
    "set $PREV name \"LEVEL\"\n"
    "set $PREV defaultvalue null\n"
    "set $PREV defaulttype 0\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n"
    "add /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH columns MANAGER_ID\n"
    "set /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH/columns#MANAGER_ID index 2\n"
    "set $PREV type 5\n"
    "set $PREV size 4\n"
    "set $PREV nullable false\n"
    "set $PREV name \"MANAGER_ID\"\n"
    "set $PREV defaultvalue null\n"
    "set $PREV defaulttype 0\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n"
    "add /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH columns PATH\n"
    "set /clusters#cluster/databases#database/tables#DERIVED_EMP_PATH/columns#PATH index 4\n"
    "set $PREV type 9\n"
    "set $PREV size 10000\n"
    "set $PREV nullable false\n"
    "set $PREV name \"PATH\"\n"
    "set $PREV defaultvalue null\n"
    "set $PREV defaulttype 0\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n"
    "add /clusters#cluster/databases#database tables EMPLOYEES\n"
    "set /clusters#cluster/databases#database/tables#EMPLOYEES isreplicated true\n"
    "set $PREV partitioncolumn null\n"
    "set $PREV estimatedtuplecount 0\n"
    "set $PREV materializer null\n"
    "set $PREV signature \"EMPLOYEES|vii\"\n"
    "set $PREV tuplelimit 2147483647\n"
    "set $PREV isDRed false\n"
    "add /clusters#cluster/databases#database/tables#EMPLOYEES columns EMP_ID\n"
    "set /clusters#cluster/databases#database/tables#EMPLOYEES/columns#EMP_ID index 1\n"
    "set $PREV type 5\n"
    "set $PREV size 4\n"
    "set $PREV nullable false\n"
    "set $PREV name \"EMP_ID\"\n"
    "set $PREV defaultvalue null\n"
    "set $PREV defaulttype 0\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n"
    "add /clusters#cluster/databases#database/tables#EMPLOYEES columns LAST_NAME\n"
    "set /clusters#cluster/databases#database/tables#EMPLOYEES/columns#LAST_NAME index 0\n"
    "set $PREV type 9\n"
    "set $PREV size 20\n"
    "set $PREV nullable false\n"
    "set $PREV name \"LAST_NAME\"\n"
    "set $PREV defaultvalue null\n"
    "set $PREV defaulttype 0\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n"
    "add /clusters#cluster/databases#database/tables#EMPLOYEES columns MANAGER_ID\n"
    "set /clusters#cluster/databases#database/tables#EMPLOYEES/columns#MANAGER_ID index 2\n"
    "set $PREV type 5\n"
    "set $PREV size 4\n"
    "set $PREV nullable true\n"
    "set $PREV name \"MANAGER_ID\"\n"
    "set $PREV defaultvalue null\n"
    "set $PREV defaulttype 0\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n"
    "add /clusters#cluster/databases#database snapshotSchedule default\n"
    "set /clusters#cluster/databases#database/snapshotSchedule#default enabled false\n"
    "set $PREV frequencyUnit \"h\"\n"
    "set $PREV frequencyValue 24\n"
    "set $PREV retain 2\n"
    "set $PREV prefix \"AUTOSNAP\"\n"
    "add /clusters#cluster deployment deployment\n"
    "set /clusters#cluster/deployment#deployment kfactor 0\n"
    "add /clusters#cluster/deployment#deployment systemsettings systemsettings\n"
    "set /clusters#cluster/deployment#deployment/systemsettings#systemsettings temptablemaxsize 100\n"
    "set $PREV snapshotpriority 6\n"
    "set $PREV elasticduration 50\n"
    "set $PREV elasticthroughput 2\n"
    "set $PREV querytimeout 10000\n"
    "add /clusters#cluster logconfig log\n"
    "set /clusters#cluster/logconfig#log enabled false\n"
    "set $PREV synchronous false\n"
    "set $PREV fsyncInterval 200\n"
    "set $PREV maxTxns 2147483647\n"
    "set $PREV logSize 1024\n";

const std::string jsonPlan =
    "{\n"
    "    \"EXECUTE_LISTS\": [\n"
    "        {\"EXECUTE_LIST\": [\n"
    "            2,\n"
    "            1\n"
    "        ]},\n"
    "        {\"EXECUTE_LIST\": [\n"
    "            5,\n"
    "            4\n"
    "        ]},\n"
    "        {\"EXECUTE_LIST\": [\n"
    "            10,\n"
    "            12,\n"
    "            9,\n"
    "            8\n"
    "        ]}\n"
    "    ],\n"
    "    \"IS_LARGE_QUERY\": false,\n"
    "    \"PLAN_NODES_LISTS\": [\n"
    "        {\n"
    "            \"PLAN_NODES\": [\n"
    "                {\n"
    "                    \"CHILDREN_IDS\": [2],\n"
    "                    \"ID\": 1,\n"
    "                    \"PLAN_NODE_TYPE\": \"SEND\"\n"
    "                },\n"
    "                {\n"
    "                    \"ID\": 2,\n"
    "                    \"INLINE_NODES\": [{\n"
    "                        \"ID\": 3,\n"
    "                        \"OUTPUT_SCHEMA\": [\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"LAST_NAME\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 0,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_SIZE\": 20,\n"
    "                                    \"VALUE_TYPE\": 9\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"EMP_ID\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 1,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"MANAGER_ID\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 2,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"LEVEL\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 3,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"PATH\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 4,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_SIZE\": 10000,\n"
    "                                    \"VALUE_TYPE\": 9\n"
    "                                }\n"
    "                            }\n"
    "                        ],\n"
    "                        \"PLAN_NODE_TYPE\": \"PROJECTION\"\n"
    "                    }],\n"
    "                    \"PLAN_NODE_TYPE\": \"SEQSCAN\",\n"
    "                    \"TARGET_TABLE_ALIAS\": \"EMP_PATH\",\n"
    "                    \"TARGET_TABLE_NAME\": \"EMP_PATH\",\n"
    "                    \"IS_CTE_SCAN\": true\n"
    "                }\n"
    "            ],\n"
    "            \"STATEMENT_ID\": 0\n"
    "        },\n"
    "        {\n"
    "            \"PLAN_NODES\": [\n"
    "                {\n"
    "                    \"CHILDREN_IDS\": [5],\n"
    "                    \"ID\": 4,\n"
    "                    \"PLAN_NODE_TYPE\": \"RECURSIVECTE\",\n"
    "                    \"RECURSIVE_STATEMENT_ID\": 2\n"
    "                },\n"
    "                {\n"
    "                    \"ID\": 5,\n"
    "                    \"INLINE_NODES\": [{\n"
    "                        \"ID\": 6,\n"
    "                        \"OUTPUT_SCHEMA\": [\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"LAST_NAME\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 0,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_SIZE\": 20,\n"
    "                                    \"VALUE_TYPE\": 9\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"EMP_ID\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 1,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"MANAGER_ID\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 2,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"C4\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"PARAM_IDX\": 0,\n"
    "                                    \"TYPE\": 31,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"LAST_NAME\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 0,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_SIZE\": 20,\n"
    "                                    \"VALUE_TYPE\": 9\n"
    "                                }\n"
    "                            }\n"
    "                        ],\n"
    "                        \"PLAN_NODE_TYPE\": \"PROJECTION\"\n"
    "                    }],\n"
    "                    \"PLAN_NODE_TYPE\": \"SEQSCAN\",\n"
    "                    \"PREDICATE\": {\n"
    "                        \"LEFT\": {\n"
    "                            \"COLUMN_IDX\": 2,\n"
    "                            \"TYPE\": 32,\n"
    "                            \"VALUE_TYPE\": 5\n"
    "                        },\n"
    "                        \"TYPE\": 9,\n"
    "                        \"VALUE_TYPE\": 23\n"
    "                    },\n"
    "                    \"TARGET_TABLE_ALIAS\": \"EMPLOYEES\",\n"
    "                    \"TARGET_TABLE_NAME\": \"EMPLOYEES\"\n"
    "                }\n"
    "            ],\n"
    "            \"STATEMENT_ID\": 1\n"
    "        },\n"
    "        {\n"
    "            \"PLAN_NODES\": [\n"
    "                {\n"
    "                    \"CHILDREN_IDS\": [9],\n"
    "                    \"ID\": 8,\n"
    "                    \"OUTPUT_SCHEMA\": [\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"LAST_NAME\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"COLUMN_IDX\": 0,\n"
    "                                \"TYPE\": 32,\n"
    "                                \"VALUE_SIZE\": 20,\n"
    "                                \"VALUE_TYPE\": 9\n"
    "                            }\n"
    "                        },\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"EMP_ID\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"COLUMN_IDX\": 1,\n"
    "                                \"TYPE\": 32,\n"
    "                                \"VALUE_TYPE\": 5\n"
    "                            }\n"
    "                        },\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"MANAGER_ID\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"COLUMN_IDX\": 2,\n"
    "                                \"TYPE\": 32,\n"
    "                                \"VALUE_TYPE\": 5\n"
    "                            }\n"
    "                        },\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"C4\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"LEFT\": {\n"
    "                                    \"COLUMN_IDX\": 4,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                },\n"
    "                                \"RIGHT\": {\n"
    "                                    \"PARAM_IDX\": 0,\n"
    "                                    \"TYPE\": 31,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                },\n"
    "                                \"TYPE\": 1,\n"
    "                                \"VALUE_TYPE\": 6\n"
    "                            }\n"
    "                        },\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"C5\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"ARGS\": [\n"
    "                                    {\n"
    "                                        \"ARGS\": [\n"
    "                                            {\n"
    "                                                \"COLUMN_IDX\": 5,\n"
    "                                                \"TYPE\": 32,\n"
    "                                                \"VALUE_SIZE\": 10000,\n"
    "                                                \"VALUE_TYPE\": 9\n"
    "                                            },\n"
    "                                            {\n"
    "                                                \"PARAM_IDX\": 1,\n"
    "                                                \"TYPE\": 31,\n"
    "                                                \"VALUE_SIZE\": 1048576,\n"
    "                                                \"VALUE_TYPE\": 9\n"
    "                                            }\n"
    "                                        ],\n"
    "                                        \"FUNCTION_ID\": 124,\n"
    "                                        \"NAME\": \"concat\",\n"
    "                                        \"TYPE\": 100,\n"
    "                                        \"VALUE_SIZE\": 1048576,\n"
    "                                        \"VALUE_TYPE\": 9\n"
    "                                    },\n"
    "                                    {\n"
    "                                        \"COLUMN_IDX\": 0,\n"
    "                                        \"TYPE\": 32,\n"
    "                                        \"VALUE_SIZE\": 20,\n"
    "                                        \"VALUE_TYPE\": 9\n"
    "                                    }\n"
    "                                ],\n"
    "                                \"FUNCTION_ID\": 124,\n"
    "                                \"NAME\": \"concat\",\n"
    "                                \"TYPE\": 100,\n"
    "                                \"VALUE_SIZE\": 1048576,\n"
    "                                \"VALUE_TYPE\": 9\n"
    "                            }\n"
    "                        }\n"
    "                    ],\n"
    "                    \"PLAN_NODE_TYPE\": \"PROJECTION\"\n"
    "                },\n"
    "                {\n"
    "                    \"CHILDREN_IDS\": [\n"
    "                        10,\n"
    "                        12\n"
    "                    ],\n"
    "                    \"ID\": 9,\n"
    "                    \"JOIN_PREDICATE\": {\n"
    "                        \"LEFT\": {\n"
    "                            \"COLUMN_IDX\": 0,\n"
    "                            \"TABLE_IDX\": 1,\n"
    "                            \"TYPE\": 32,\n"
    "                            \"VALUE_TYPE\": 5\n"
    "                        },\n"
    "                        \"RIGHT\": {\n"
    "                            \"COLUMN_IDX\": 2,\n"
    "                            \"TYPE\": 32,\n"
    "                            \"VALUE_TYPE\": 5\n"
    "                        },\n"
    "                        \"TYPE\": 10,\n"
    "                        \"VALUE_TYPE\": 23\n"
    "                    },\n"
    "                    \"JOIN_TYPE\": \"INNER\",\n"
    "                    \"OUTPUT_SCHEMA\": [\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"LAST_NAME\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"COLUMN_IDX\": 0,\n"
    "                                \"TYPE\": 32,\n"
    "                                \"VALUE_SIZE\": 20,\n"
    "                                \"VALUE_TYPE\": 9\n"
    "                            }\n"
    "                        },\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"EMP_ID\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"COLUMN_IDX\": 1,\n"
    "                                \"TYPE\": 32,\n"
    "                                \"VALUE_TYPE\": 5\n"
    "                            }\n"
    "                        },\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"MANAGER_ID\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"COLUMN_IDX\": 2,\n"
    "                                \"TYPE\": 32,\n"
    "                                \"VALUE_TYPE\": 5\n"
    "                            }\n"
    "                        },\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"EMP_ID\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"COLUMN_IDX\": 3,\n"
    "                                \"TYPE\": 32,\n"
    "                                \"VALUE_TYPE\": 5\n"
    "                            }\n"
    "                        },\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"LEVEL\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"COLUMN_IDX\": 4,\n"
    "                                \"TYPE\": 32,\n"
    "                                \"VALUE_TYPE\": 5\n"
    "                            }\n"
    "                        },\n"
    "                        {\n"
    "                            \"COLUMN_NAME\": \"PATH\",\n"
    "                            \"EXPRESSION\": {\n"
    "                                \"COLUMN_IDX\": 5,\n"
    "                                \"TYPE\": 32,\n"
    "                                \"VALUE_SIZE\": 10000,\n"
    "                                \"VALUE_TYPE\": 9\n"
    "                            }\n"
    "                        }\n"
    "                    ],\n"
    "                    \"PLAN_NODE_TYPE\": \"NESTLOOP\",\n"
    "                    \"PRE_JOIN_PREDICATE\": null,\n"
    "                    \"WHERE_PREDICATE\": null\n"
    "                },\n"
    "                {\n"
    "                    \"ID\": 10,\n"
    "                    \"INLINE_NODES\": [{\n"
    "                        \"ID\": 11,\n"
    "                        \"OUTPUT_SCHEMA\": [\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"LAST_NAME\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 0,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_SIZE\": 20,\n"
    "                                    \"VALUE_TYPE\": 9\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"EMP_ID\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 1,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"MANAGER_ID\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 2,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                }\n"
    "                            }\n"
    "                        ],\n"
    "                        \"PLAN_NODE_TYPE\": \"PROJECTION\"\n"
    "                    }],\n"
    "                    \"PLAN_NODE_TYPE\": \"SEQSCAN\",\n"
    "                    \"TARGET_TABLE_ALIAS\": \"E\",\n"
    "                    \"TARGET_TABLE_NAME\": \"EMPLOYEES\"\n"
    "                },\n"
    "                {\n"
    "                    \"ID\": 12,\n"
    "                    \"INLINE_NODES\": [{\n"
    "                        \"ID\": 13,\n"
    "                        \"OUTPUT_SCHEMA\": [\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"EMP_ID\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 1,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"LEVEL\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 3,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_TYPE\": 5\n"
    "                                }\n"
    "                            },\n"
    "                            {\n"
    "                                \"COLUMN_NAME\": \"PATH\",\n"
    "                                \"EXPRESSION\": {\n"
    "                                    \"COLUMN_IDX\": 4,\n"
    "                                    \"TYPE\": 32,\n"
    "                                    \"VALUE_SIZE\": 10000,\n"
    "                                    \"VALUE_TYPE\": 9\n"
    "                                }\n"
    "                            }\n"
    "                        ],\n"
    "                        \"PLAN_NODE_TYPE\": \"PROJECTION\"\n"
    "                    }],\n"
    "                    \"PLAN_NODE_TYPE\": \"SEQSCAN\",\n"
    "                    \"TARGET_TABLE_ALIAS\": \"EP\",\n"
    "                    \"TARGET_TABLE_NAME\": \"EMP_PATH\","
    "                    \"IS_CTE_SCAN\": true\n"
    "                }\n"
    "            ],\n"
    "            \"STATEMENT_ID\": 2\n"
    "        }\n"
    "    ]\n"
    "}\n";

TEST_F(RecursiveCommonTableExpressionTest, Basic) {
    UniqueEngine engine = UniqueEngineBuilder().build();
    bool success = engine->loadCatalog(0, catalogPayload);
    ASSERT_TRUE(success);

    auto ev = ExecutorVector::fromJsonPlan(engine.get(), jsonPlan, 0);
    ASSERT_NE(NULL, ev.get());
}

int main() {
    return TestSuite::globalInstance()->runAll();
}
