CREATE TABLE t1 (a VARCHAR(5) NOT NULL, b VARCHAR(65), c VARCHAR(5));
CREATE VIEW mv (b, a, total) AS SELECT b, a, COUNT(*) FROM t1 GROUP BY b, a;
CREATE INDEX i1 ON t1 (b);
CREATE INDEX i2 ON t1 (a, b);
