#!/bin/sh
# Converts VoltDB version number to standard format
#   as per 'semantic versioning' -- 'n.n.n-xxx'
# Version number is supplied by standard input.
awk '{
  if ($0 ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) print
  else if ($0 !~ /^[0-9]/) print
  else { match($0, /^[0-9]+(\.[0-9]+)*/)
         F = substr($0,RSTART,RLENGTH); B = substr($0,RSTART+RLENGTH)
         while (split(F,A,".") < 3) F = F ".0"
         sub(/^(-|\.)+/, "", B)
         if (length(B) > 0) B = "-" B
         print(F B)
       }
}'
