CREATE TABLE P1 (
  ID INTEGER NOT NULL,
  VCHAR VARCHAR(300),
  NUM INTEGER,
  RATIO FLOAT,
  CONSTRAINT P1_PK_TREE PRIMARY KEY (ID)
);
CREATE INDEX P1_IDX_NUM_VCHAR_RATIO_TREE ON P1 (NUM, VCHAR, RATIO);
CREATE INDEX P1_IDX_RATIO_VCHAR_NUM_TREE ON P1 (RATIO, VCHAR, NUM);
CREATE INDEX P1_IDX_VCHAR_NUM_RATIO_TREE ON P1 (VCHAR, NUM, RATIO);
CREATE INDEX P1_IDX_NUM_RATIO_VCHAR_TREE ON P1 (NUM, RATIO, VCHAR);

PARTITION TABLE P1 ON COLUMN ID;

CREATE TABLE R1 (
  ID INTEGER NOT NULL,
  VCHAR VARCHAR(300),
  NUM INTEGER,
  RATIO FLOAT,
  CONSTRAINT R1_PK_TREE PRIMARY KEY (ID)
--  PRIMARY KEY (ID)
);
CREATE INDEX R1_IDX_NUM_VCHAR_RATIO_TREE ON R1 (NUM, VCHAR, RATIO);
CREATE INDEX R1_IDX_RATIO_VCHAR_NUM_TREE ON R1 (RATIO, VCHAR, NUM);
CREATE INDEX R1_IDX_VCHAR_NUM_RATIO_TREE ON R1 (VCHAR, NUM, RATIO);
CREATE INDEX R1_IDX_NUM_RATIO_VCHAR_TREE ON R1 (NUM, RATIO, VCHAR);

CREATE TABLE R2 (
  ID INTEGER NOT NULL,
  VCHAR VARCHAR(300),
  NUM INTEGER,
  RATIO FLOAT,
  CONSTRAINT R2_PK_TREE PRIMARY KEY (ID)
--  PRIMARY KEY (ID)
);
CREATE INDEX R2_IDX_NUM_VCHAR_RATIO_TREE ON R2 (NUM, VCHAR);
CREATE INDEX R2_IDX_RATIO_VCHAR_NUM_TREE ON R2 (RATIO, VCHAR);
CREATE INDEX R2_IDX_VCHAR_NUM_RATIO_TREE ON R2 (VCHAR, NUM);
CREATE INDEX R2_IDX_NUM_RATIO_VCHAR_TREE ON R2 (NUM, RATIO);
