CREATE TABLE PARTIAL_COVERING_TREE (
  ID INTEGER NOT NULL,
  A1 INTEGER NOT NULL,
  A2 INTEGER NOT NULL,
  A3 INTEGER NOT NULL,
  A4 INTEGER NOT NULL
);
CREATE INDEX PC_TREE_A1A2 ON PARTIAL_COVERING_TREE (A1, A2);
CREATE INDEX PC_TREE_A2A3A4 ON PARTIAL_COVERING_TREE (A2, A3, A4);

CREATE TABLE PARTIAL_COVERING_HASH (
  ID INTEGER NOT NULL,
  A1 INTEGER NOT NULL,
  A2 INTEGER NOT NULL,
  A3 INTEGER NOT NULL,
  A4 INTEGER NOT NULL
);
CREATE INDEX PC_HASH_A1A2 ON PARTIAL_COVERING_HASH (A1, A2);
CREATE INDEX PC_HASH_A2A3A4 ON PARTIAL_COVERING_HASH (A2, A3, A4);

