CREATE TABLE P1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  VCHAR VARCHAR(64 BYTES),
  VCHAR_INLINE_MAX VARCHAR(15),
  VCHAR_INLINE VARCHAR(42 BYTES),
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (ID)
);
PARTITION TABLE P1 ON COLUMN ID;

CREATE TABLE R1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  VCHAR VARCHAR(5000),
  VCHAR_INLINE_MAX VARCHAR(63 BYTES),
  VCHAR_INLINE VARCHAR(14),
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (ID)
);
