CREATE TABLE P1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  PAST TIMESTAMP NOT NULL,
  FUTURE TIMESTAMP NOT NULL,
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE R1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  PAST TIMESTAMP NOT NULL,
  FUTURE TIMESTAMP NOT NULL,
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (ID)
);
PARTITION TABLE P1 ON COLUMN ID;
