CREATE TABLE hashtags (
    hashtag VARCHAR(256) NOT NULL,
    tweet_timestamp BIGINT NOT NULL
);

CREATE TABLE tweets (
    username VARCHAR(256) NOT NULL,
    tweet_timestamp BIGINT NOT NULL
);

PARTITION TABLE hashtags ON COLUMN hashtag;
PARTITION TABLE tweets ON COLUMN username;

CREATE PROCEDURE FROM CLASS com.eng866.Select;
CREATE PROCEDURE FROM CLASS com.eng866.Delete;
CREATE PROCEDURE PARTITION ON TABLE hashtags COLUMN hashtag FROM CLASS com.eng866.Insert;
CREATE PROCEDURE PARTITION ON TABLE tweets COLUMN username AS INSERT INTO tweets VALUES (?, ?);
