-- Define the tables used by the SQLCoverage Geo tests

CREATE TABLE P1 (
  ID INTEGER NOT NULL,
  PT1 GEOGRAPHY_POINT,
  PT2 GEOGRAPHY_POINT,
  PT3 GEOGRAPHY_POINT,
  POLY1 GEOGRAPHY,
  POLY2 GEOGRAPHY,
  POLY3 GEOGRAPHY,
  RATIO FLOAT,
  PRIMARY KEY (ID)
);
PARTITION TABLE P1 ON COLUMN ID;

CREATE TABLE R1 (
  ID INTEGER NOT NULL,
  PT1 GEOGRAPHY_POINT,
  PT2 GEOGRAPHY_POINT,
  PT3 GEOGRAPHY_POINT,
  POLY1 GEOGRAPHY,
  POLY2 GEOGRAPHY,
  POLY3 GEOGRAPHY,
  RATIO FLOAT,
  PRIMARY KEY (ID)
);
