CREATE TABLE P1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(300),
  NUM INTEGER NOT NULL,
  RATIO FLOAT NOT NULL,
  CONSTRAINT P1_PK_TREE PRIMARY KEY (ID)
);
CREATE INDEX P1_IDX_NUM_TREE ON P1 (NUM);
CREATE INDEX P1_IDX_RATIO_TREE ON P1 (RATIO);
CREATE INDEX P1_IDX_DESC_TREE ON P1 (DESC);

CREATE TABLE R1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(300),
  NUM INTEGER NOT NULL,
  RATIO FLOAT NOT NULL,
  CONSTRAINT R1_PK_TREE PRIMARY KEY (ID)
--  PRIMARY KEY (ID)
);
CREATE INDEX R1_IDX_NUM_TREE ON R1 (NUM);
CREATE INDEX R1_IDX_RATIO_TREE ON R1 (RATIO);
CREATE INDEX R1_IDX_DESC_TREE ON R1 (DESC);
