CREATE TABLE P1 (
    ID INTEGER NOT NULL,
    POINTS INTEGER NOT NULL,
    PRIMARY KEY (ID)
);
create unique index idx_P1_TREE on P1 (POINTS);

CREATE TABLE R1 (
    ID INTEGER NOT NULL,
    POINTS INTEGER NOT NULL,
    PRIMARY KEY (ID)
);
create unique index idx_R1_TREE on R1 (POINTS);
PARTITION TABLE P1 ON COLUMN ID;
