
CREATE TABLE SOURCE_P1 (
  ID INTEGER NOT NULL,
  VCHAR VARCHAR(300),
  NUM INTEGER,
  RATIO FLOAT
);
PARTITION TABLE SOURCE_P1 ON COLUMN ID;

CREATE TABLE SOURCE_P2 (
  ID INTEGER NOT NULL,
  VCHAR VARCHAR(300),
  NUM INTEGER,
  RATIO FLOAT
);
PARTITION TABLE SOURCE_P2 ON COLUMN ID;

CREATE TABLE SOURCE_R1 (
  ID INTEGER NOT NULL,
  VCHAR VARCHAR(300),
  NUM INTEGER,
  RATIO FLOAT
);

CREATE TABLE TARGET_P1 (
  ID INTEGER NOT NULL,
  VCHAR VARCHAR(300),
  NUM INTEGER,
  RATIO FLOAT
);
PARTITION TABLE TARGET_P1 ON COLUMN ID;
