CREATE TABLE P1 (
  ID INTEGER NOT NULL,
  TINY TINYINT NOT NULL,
  SMALL SMALLINT NOT NULL,
  BIG BIGINT NOT NULL,
  PRIMARY KEY (ID)
);
PARTITION TABLE P1 ON COLUMN ID;

CREATE TABLE R1 (
  ID INTEGER NOT NULL,
  TINY TINYINT NOT NULL,
  SMALL SMALLINT NOT NULL,
  BIG BIGINT NOT NULL,
  PRIMARY KEY (ID)
);

-- Only used with matview-schema.py, which needs work
CREATE VIEW MATP1 (BIG, ID, NUM, IDCOUNT, TINYCOUNT, SMALLCOUNT, BIGCOUNT, TINYSUM, SMALLSUM) AS
  SELECT BIG, ID, COUNT(*), COUNT(ID), COUNT(TINY), COUNT(SMALL), COUNT(BIG), SUM(TINY), SUM(SMALL)
  FROM P1
  GROUP BY BIG, ID;

CREATE VIEW MATR1 (BIG, NUM, TINYSUM, SMALLSUM) AS
  SELECT BIG, COUNT(*), SUM(TINY), SUM(SMALL)
  FROM R1 WHERE ID > 5
  GROUP BY BIG;
