CREATE TABLE P1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  TINY TINYINT NOT NULL,
  SMALL SMALLINT NOT NULL,
  BIG BIGINT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE R1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  TINY TINYINT NOT NULL,
  SMALL SMALLINT NOT NULL,
  BIG BIGINT NOT NULL,
  PRIMARY KEY (ID)
);
