-- DML, generate random data first.
--INSERT
-- test basic INSERT
INSERT INTO _table VALUES (@insertvals)

SELECT * FROM P1 LHS23 LEFT  JOIN R1 RHS ON    LHS23.ID = RHS.ID AND     RHS.ID = 2
SELECT * FROM R1 LHS24 RIGHT JOIN P1 RHS ON    LHS24.ID = RHS.ID AND     LHS24.ID = 2
SELECT * FROM P1 LHS24 LEFT  JOIN R1 RHS ON    LHS24.ID = RHS.ID AND     LHS24.ID = 2
SELECT * FROM R1 LHS23 RIGHT JOIN P1 RHS ON    LHS23.ID = RHS.ID AND     RHS.ID = 2
SELECT * FROM P1 LHS23 RIGHT JOIN R1 RHS ON    LHS23.ID = RHS.ID AND     RHS.ID = 2
SELECT * FROM R1 LHS24 LEFT  JOIN P1 RHS ON    LHS24.ID = RHS.ID AND     LHS24.ID = 2
SELECT * FROM P1 LHS24 RIGHT JOIN R1 RHS ON    LHS24.ID = RHS.ID AND     LHS24.ID = 2
SELECT * FROM R1 LHS23 LEFT  JOIN P1 RHS ON    LHS23.ID = RHS.ID AND     RHS.ID = 2


SELECT * FROM P1 LEFT  JOIN R1 USING(ID, NUM) WHERE ID > 10 AND NUM < 30 AND ID = NUM
SELECT * FROM R1 RIGHT JOIN P1 USING(ID, NUM) WHERE ID > 10 AND NUM < 30 AND ID = NUM
SELECT * FROM P1 RIGHT JOIN R1 USING(ID, NUM) WHERE ID > 10 AND NUM < 30 AND ID = NUM
SELECT * FROM R1 LEFT  JOIN P1 USING(ID, NUM) WHERE ID > 10 AND NUM < 30 AND ID = NUM
