CREATE TABLE P1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(64 BYTES),
  DESC_INLINE_MAX VARCHAR(15),
  DESC_INLINE VARCHAR(42 BYTES),
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE R1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(5000),
  DESC_INLINE_MAX VARCHAR(63 BYTES),
  DESC_INLINE VARCHAR(14),
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (ID)
);
PARTITION TABLE P1 ON COLUMN ID;
