/* This file is part of VoltDB.
 * Copyright (C) 2008-2022 Volt Active Data Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/*
    CREATE TABLE a (
        last_update timestamp default now not null
    ) USING TTL 1 SECONDS ON COLUMN last_update BATCH_SIZE 2
        MIGRATE TO TARGET archive;
*/
const char *catalogPayloadBasic =
    "add / clusters cluster\n"
    "set /clusters#cluster localepoch 1199145600\n"
    "set $PREV securityEnabled false\n"
    "set $PREV httpdportno 0\n"
    "set $PREV jsonapi true\n"
    "set $PREV networkpartition true\n"
    "set $PREV heartbeatTimeout 90\n"
    "set $PREV useddlschema true\n"
    "set $PREV drConsumerEnabled false\n"
    "set $PREV drProducerEnabled false\n"
    "set $PREV drRole \"none\"\n"
    "set $PREV drClusterId 0\n"
    "set $PREV drProducerPort 0\n"
    "set $PREV drMasterHost \"\"\n"
    "set $PREV drConsumerSslPropertyFile \"\"\n"
    "set $PREV drFlushInterval 1\n"
    "set $PREV exportFlushInterval 1\n"
    "set $PREV preferredSource 0\n"
    "add /clusters#cluster databases database\n"
    "set /clusters#cluster/databases#database schema \"xwJUNDM1MjQ1NDE1NDQ1MjA1NDQxNDI0QwEMHDYxMjAyODIwPgIAfDZDNjE3Mzc0NUY3NTcwNjQ2MTc0NjUyMDc0Njk2RDY1ARwYNjE2RDcwMgEeSDU2NjYxNzU2Qzc0MjA2RTZGNzcNCAUQARoENkMdZDA5MjA1NTUzNDk0RTQ3AZJkNTQ0QzIwMzEyMDUzNDU0MzRGNEU0NDUzMjABCgQyMAUSIEM1NTRENEUyMF6eAAQ0MgXkKDM0ODVGNTM0OTVBAeQEMzIdeg3qGDRENDk0NzUJMCkUBEYyJRoYNTI0NzQ1NQG4PDE3MjYzNjg2OTc2NjUzQgo=\"\n"
    "set $PREV isActiveActiveDRed false\n"
    "set $PREV securityprovider \"hash\"\n"
    "add /clusters#cluster/databases#database groups administrator\n"
    "set /clusters#cluster/databases#database/groups#administrator admin true\n"
    "set $PREV defaultproc true\n"
    "set $PREV defaultprocread true\n"
    "set $PREV sql true\n"
    "set $PREV sqlread true\n"
    "set $PREV allproc true\n"
    "add /clusters#cluster/databases#database groups user\n"
    "set /clusters#cluster/databases#database/groups#user admin false\n"
    "set $PREV defaultproc true\n"
    "set $PREV defaultprocread true\n"
    "set $PREV sql true\n"
    "set $PREV sqlread true\n"
    "set $PREV allproc true\n"
    "add /clusters#cluster/databases#database tables A\n"
    "set /clusters#cluster/databases#database/tables#A isreplicated true\n"
    "set $PREV partitioncolumn null\n"
    "set $PREV estimatedtuplecount 0\n"
    "set $PREV materializer null\n"
    "set $PREV signature \"A|p\"\n"
    "set $PREV tuplelimit 2147483647\n"
    "set $PREV isDRed false\n"
    "set $PREV tableType 4\n"
    "add /clusters#cluster/databases#database/tables#A columns LAST_UPDATE\n"
    "set /clusters#cluster/databases#database/tables#A/columns#LAST_UPDATE index 0\n"
    "set $PREV type 11\n"
    "set $PREV size 8\n"
    "set $PREV nullable false\n"
    "set $PREV name \"LAST_UPDATE\"\n"
    "set $PREV defaultvalue \"CURRENT_TIMESTAMP:43\"\n"
    "set $PREV defaulttype 11\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n"
    "add /clusters#cluster/databases#database/tables#A timeToLive ttl\n"
    "set /clusters#cluster/databases#database/tables#A/timeToLive#ttl ttlValue 1\n"
    "set $PREV ttlUnit \"SECONDS\"\n"
    "set $PREV ttlColumn /clusters#cluster/databases#database/tables#A/columns#LAST_UPDATE\n"
    "set $PREV batchSize 2\n"
    "set $PREV maxFrequency 1\n"
    "set $PREV migrationTarget \"ARCHIVE\"\n"
    "add /clusters#cluster/databases#database connectors ARCHIVE\n"
    "set /clusters#cluster/databases#database/connectors#ARCHIVE loaderclass \"\"\n"
    "set $PREV enabled false\n"
    "add /clusters#cluster/databases#database/connectors#ARCHIVE tableInfo A\n"
    "set /clusters#cluster/databases#database/connectors#ARCHIVE/tableInfo#A table /clusters#cluster/databases#database/tables#A\n"
    "set $PREV appendOnly true\n"
    "add /clusters#cluster/databases#database snapshotSchedule default\n"
    "set /clusters#cluster/databases#database/snapshotSchedule#default enabled false\n"
    "set $PREV frequencyUnit \"h\"\n"
    "set $PREV frequencyValue 24\n"
    "set $PREV retain 2\n"
    "set $PREV prefix \"AUTOSNAP\"\n"
    "add /clusters#cluster deployment deployment\n"
    "set /clusters#cluster/deployment#deployment kfactor 0\n"
    "add /clusters#cluster/deployment#deployment systemsettings systemsettings\n"
    "set /clusters#cluster/deployment#deployment/systemsettings#systemsettings temptablemaxsize 100\n"
    "set $PREV snapshotpriority 6\n"
    "set $PREV elasticduration 50\n"
    "set $PREV elasticthroughput 2\n"
    "set $PREV querytimeout 10000\n"
    "add /clusters#cluster logconfig log\n"
    "set /clusters#cluster/logconfig#log enabled false\n"
    "set $PREV synchronous false\n"
    "set $PREV fsyncInterval 200\n"
    "set $PREV maxTxns 2147483647\n"
    "set $PREV logSize 1024\n";

// ALTER TABLE a ADD COLUMN a INT NOT NULL;
const char *catalogPayloadAddColumnA =
    "set /clusters#cluster/databases#database schema \"tgNUNDM1MjQ1NDE1NDQ1MjA1NDQxNDI0QwEMHDQxMjAyODIwCQI8NEM0MTUzNTQ1RjU1NTA0NBEySDc0Njk2RDY1NzM3NDYxNkQ3MDIBHkg1NDY0MTU1NEM1NDIwNDM1NTUyBWgARQVCGDQ0OTRENDUBUBA0MTRENQE0CEU0RgUsAEUBNkQ0QzIwMjkyMDU1NTM0OTRFNDcBnAQ1NAEYTDMxMjA1MzQ1NDM0RjRFNDQ1MzIwAQoBaCA0RjRDNTU0RDQBDlqyAAQ0MgW8KDM0ODVGNTM0OTVBAe40MzIyMDRENDE1ODVGNDYBrAA1AcAcNTRFNDM1OTIFdgUiDDk0NzUJQikwDEYyMDUhDhAyNDc0NQXCCDE1MgFeDDQ5NTYBJBAzQgo0MSEJDDQ1NTIJLTFjJDYxMjA0MTQ0NDQ+vQAFGgg5NEUFUTobAQgzQgo=\"\n"
    "set /clusters#cluster/databases#database/tables#A signature \"A|pi\"\n"
    "add /clusters#cluster/databases#database/tables#A columns A\n"
    "set /clusters#cluster/databases#database/tables#A/columns#A index 1\n"
    "set $PREV type 5\n"
    "set $PREV size 4\n"
    "set $PREV nullable false\n"
    "set $PREV name \"A\"\n"
    "set $PREV defaultvalue null\n"
    "set $PREV defaulttype 0\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n";

// CREATE INDEX idx_a ON a (last_update) WHERE NOT MIGRATING;
const char *catalogPayloadCreateIndex =
    "set /clusters#cluster/databases#database schema \"iARUNDM1MjQ1NDE1NDQ1MjA1NDQxNDI0QwEMHDQxMjAyODIwCQI8NEM0MTUzNTQ1RjU1NTA0NBEySDc0Njk2RDY1NzM3NDYxNkQ3MDIBHkg1NDY0MTU1NEM1NDIwNDM1NTUyBWgARQVCGDQ0OTRENDUBUBA0MTRENQE0CEU0RgUsAEUBNgw0QzJDCXgAMgWIPDY5NkU3NDY1Njc2NTcyMjBCLgA4MDI5MjA1NTUzNDk0RTQ3AcpkNTQ0QzIwMzEyMDUzNDU0MzRGNEU0NDUzMjABCgGWIDRGNEM1NTRENAEOWuAABDQyBeoQMzQ4NUYBXgQ1QSEcADMBhCBENDE1ODVGNDYB2gA1Ae4YNTRFNDM1OQl2IDIwNEQ0OTQ3NQlCKV4ERjIlZBQ1MjQ3NDUF8AEMGDM0ODQ5NTYBJAgzQgo2kwEF0RQ0NDU1ODIhBxw0Nzg1RjYxMg3FAQpMMjg2QzYxNzM3NDVGNzU3MDY0NjEhLSUTEDc0ODQ1AaE9NS6XABw5NEU0NzNCCg==\"\n"
    "add /clusters#cluster/databases#database/tables#A indexes IDX_A\n"
    "set /clusters#cluster/databases#database/tables#A/indexes#IDX_A unique false\n"
    "set $PREV assumeUnique false\n"
    "set $PREV migrating true\n"
    "set $PREV countable true\n"
    "set $PREV type 1\n"
    "set $PREV expressionsjson \"\"\n"
    "set $PREV predicatejson \"{\"TYPE\":8,\"VALUE_TYPE\":1,\"VALUE_SIZE\":0,\"LEFT\":{\"TYPE\":100,\"VALUE_TYPE\":23,\"ARGS\":[],\"NAME\":\"migrating\",\"FUNCTION_ID\":21026}}\"\n"
    "set $PREV isSafeWithNonemptySources false\n"
    "add /clusters#cluster/databases#database/tables#A/indexes#IDX_A columns LAST_UPDATE\n"
    "set /clusters#cluster/databases#database/tables#A/indexes#IDX_A/columns#LAST_UPDATE index 0\n"
    "set $PREV column /clusters#cluster/databases#database/tables#A/columns#LAST_UPDATE\n";

// ALTER TABLE a USING TTL 1 SECONDS ON COLUMN last_update BATCH_SIZE 1 MIGRATE TO TARGET archive;
const char *catalogPayloadChangeBatchSize =
    "set /clusters#cluster/databases#database schema \"zwVUNDM1MjQ1NDE1NDQ1MjA1NDQxNDI0QwEMHDQxMjAyODIwCQI8NEM0MTUzNTQ1RjU1NTA0NBEySDc0Njk2RDY1NzM3NDYxNkQ3MDIBHkg1NDY0MTU1NEM1NDIwNDM1NTUyBWgARQVCGDQ0OTRENDUBUBA0MTRENQE0CEU0RgUsAEUBNgw0QzJDCXgAMgWIPDY5NkU3NDY1Njc2NTcyMjBCLgA4MDI5MjA1NTUzNDk0RTQ3AcpkNTQ0QzIwMzEyMDUzNDU0MzRGNEU0NDUzMjABCgGWIDRGNEM1NTRENAEOWuAABDQyBeoQMzQ4NUYBXgQ1QSEcADMBhCBENDE1ODVGNDYB2gA1Ae4YNTRFNDM1OQl2IDIwNEQ0OTQ3NQlCKV4ERjIlZBQ1MjQ3NDUF8AEMGDM0ODQ5NTYBJAgzQgo2kwEF0RQ0NDU1ODIBDAA0BXMEMTIRxSWlWr0AIRMQNzQ4NDUBoQwyMDI4MTckNkQ2OTY3NzI2MSW/IEU2NzI4MjkyOQF9ADEhtAEzCapRDgQ2MfZgATw2QzYxNzM3NDVGNzU3MDY0BXsENTJeYAEB4Yo+AUA2MTcyNjM2ODY5NzY2NTNCCg==\"\n"
    "set /clusters#cluster/databases#database/tables#A/timeToLive#ttl batchSize 1\n";

// ALTER TABLE a ADD COLUMN b INT;
const char *catalogPayloadAddColumnB =
    "set /clusters#cluster/databases#database schema \"zwRUNDM1MjQ1NDE1NDQ1MjA1NDQxNDI0QwEMHDQxMjAyODIwCQI8NEM0MTUzNTQ1RjU1NTA0NBEySDc0Njk2RDY1NzM3NDYxNkQ3MDIBHkg1NDY0MTU1NEM1NDIwNDM1NTUyBWgARQVCGDQ0OTRENDUBUBA0MTRENQE0CEU0RgUsAEUBNgw0QzJDCXgAMgWIPDY5NkU3NDY1Njc2NTcyMjBCLgA4MDI5MjA1NTUzNDk0RTQ3AcpkNTQ0QzIwMzEyMDUzNDU0MzRGNEU0NDUzMjABCgGWIDRGNEM1NTRENAEOWuAABDQyBeoQMzQ4NUYBXgQ1QSEcADMBhCBENDE1ODVGNDYB2gA1Ae4YNTRFNDM1OQl2IDIwNEQ0OTQ3NQlCKV4ERjIlZBQ1MjQ3NDUF8AEMGDM0ODQ5NTYBJAgzQgo2kwEF0RQ0NDU1ODIBDAA0BXMEMTIRxSWlWr0AIRMQNzQ4NDUBoQwyMDI4MTckNkQ2OTY3NzI2MSW/IEU2NzI4MjkyOQF9ADEhtAEzCapRDgA2AXMQMTQ0NDQ+OgEwNjIyMDQ5NEU1NDNCCg==\"\n"
    "set /clusters#cluster/databases#database/tables#A signature \"A|pii\"\n"
    "add /clusters#cluster/databases#database/tables#A columns B\n"
    "set /clusters#cluster/databases#database/tables#A/columns#B index 2\n"
    "set $PREV type 5\n"
    "set $PREV size 4\n"
    "set $PREV nullable true\n"
    "set $PREV name \"B\"\n"
    "set $PREV defaultvalue null\n"
    "set $PREV defaulttype 0\n"
    "set $PREV aggregatetype 0\n"
    "set $PREV matviewsource null\n"
    "set $PREV matview null\n"
    "set $PREV inbytes false\n";

// INSERT INTO a VALUES (NOW(), 1);
std::string isertPlan =
    "{\n"
    "    \"EXECUTE_LIST\": [\n"
    "        6,\n"
    "        5,\n"
    "        4\n"
    "    ],\n"
    "    \"IS_LARGE_QUERY\": false,\n"
    "    \"PLAN_NODES\": [\n"
    "        {\n"
    "            \"CHILDREN_IDS\": [5],\n"
    "            \"ID\": 4,\n"
    "            \"PLAN_NODE_TYPE\": \"SEND\"\n"
    "        },\n"
    "        {\n"
    "            \"CHILDREN_IDS\": [6],\n"
    "            \"FIELD_MAP\": [\n"
    "                0,\n"
    "                1\n"
    "            ],\n"
    "            \"ID\": 5,\n"
    "            \"MULTI_PARTITION\": true,\n"
    "            \"PLAN_NODE_TYPE\": \"INSERT\",\n"
    "            \"TARGET_TABLE_NAME\": \"A\"\n"
    "        },\n"
    "        {\n"
    "            \"BATCHED\": false,\n"
    "            \"ID\": 6,\n"
    "            \"OUTPUT_SCHEMA\": [\n"
    "                {\n"
    "                    \"COLUMN_NAME\": \"LAST_UPDATE\",\n"
    "                    \"EXPRESSION\": {\n"
    "                        \"ARGS\": [],\n"
    "                        \"FUNCTION_ID\": 43,\n"
    "                        \"NAME\": \"current_timestamp\",\n"
    "                        \"TYPE\": 100,\n"
    "                        \"VALUE_TYPE\": 11\n"
    "                    }\n"
    "                },\n"
    "                {\n"
    "                    \"COLUMN_NAME\": \"A\",\n"
    "                    \"EXPRESSION\": {\n"
    "                        \"ISNULL\": false,\n"
    "                        \"TYPE\": 30,\n"
    "                        \"VALUE\": 1,\n"
    "                        \"VALUE_TYPE\": 5\n"
    "                    }\n"
    "                }\n"
    "            ],\n"
    "            \"PLAN_NODE_TYPE\": \"MATERIALIZE\"\n"
    "        }\n"
    "    ]\n"
    "}\n";

// MIGRATE FROM A WHERE not migrating AND LAST_UPDATE <= NOW;
std::string migratePlan =
    "{\n"
    "    \"EXECUTE_LIST\": [\n"
    "        6,\n"
    "        5,\n"
    "        4\n"
    "    ],\n"
    "    \"IS_LARGE_QUERY\": false,\n"
    "    \"PLAN_NODES\": [\n"
    "        {\n"
    "            \"CHILDREN_IDS\": [5],\n"
    "            \"ID\": 4,\n"
    "            \"PLAN_NODE_TYPE\": \"SEND\"\n"
    "        },\n"
    "        {\n"
    "            \"CHILDREN_IDS\": [6],\n"
    "            \"ID\": 5,\n"
    "            \"PLAN_NODE_TYPE\": \"MIGRATE\",\n"
    "            \"TARGET_TABLE_NAME\": \"A\"\n"
    "        },\n"
    "        {\n"
    "            \"COMPARE_NOTDISTINCT\": [false],\n"
    "            \"ID\": 6,\n"
    "            \"INITIAL_EXPRESSION\": {\n"
    "                \"LEFT\": {\n"
    "                    \"COLUMN_IDX\": 0,\n"
    "                    \"TYPE\": 32,\n"
    "                    \"VALUE_TYPE\": 11\n"
    "                },\n"
    "                \"RIGHT\": {\n"
    "                    \"ARGS\": [],\n"
    "                    \"FUNCTION_ID\": 43,\n"
    "                    \"NAME\": \"current_timestamp\",\n"
    "                    \"TYPE\": 100,\n"
    "                    \"VALUE_TYPE\": 11\n"
    "                },\n"
    "                \"TYPE\": 14,\n"
    "                \"VALUE_TYPE\": 23\n"
    "            },\n"
    "            \"INLINE_NODES\": [{\n"
    "                \"ID\": 7,\n"
    "                \"OUTPUT_SCHEMA\": [{\n"
    "                    \"COLUMN_NAME\": \"tuple_address\",\n"
    "                    \"EXPRESSION\": {\n"
    "                        \"TYPE\": 33,\n"
    "                        \"VALUE_TYPE\": 6\n"
    "                    }\n"
    "                }],\n"
    "                \"PLAN_NODE_TYPE\": \"PROJECTION\"\n"
    "            }],\n"
    "            \"LOOKUP_TYPE\": \"LTE\",\n"
    "            \"PLAN_NODE_TYPE\": \"INDEXSCAN\",\n"
    "            \"PREDICATE\": {\n"
    "                \"LEFT\": {\n"
    "                    \"LEFT\": {\n"
    "                        \"COLUMN_IDX\": 0,\n"
    "                        \"TYPE\": 32,\n"
    "                        \"VALUE_TYPE\": 11\n"
    "                    },\n"
    "                    \"TYPE\": 9,\n"
    "                    \"VALUE_TYPE\": 23\n"
    "                },\n"
    "                \"TYPE\": 8,\n"
    "                \"VALUE_TYPE\": 23\n"
    "            },\n"
    "            \"SEARCHKEY_EXPRESSIONS\": [{\n"
    "                \"ARGS\": [],\n"
    "                \"FUNCTION_ID\": 43,\n"
    "                \"NAME\": \"current_timestamp\",\n"
    "                \"TYPE\": 100,\n"
    "                \"VALUE_TYPE\": 11\n"
    "            }],\n"
    "            \"SORT_DIRECTION\": \"INVALID\",\n"
    "            \"TARGET_INDEX_NAME\": \"IDX_A\",\n"
    "            \"TARGET_TABLE_ALIAS\": \"A\",\n"
    "            \"TARGET_TABLE_NAME\": \"A\"\n"
    "        }\n"
    "    ]\n"
    "}\n";
