CREATE TABLE T1 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	PRIMARY KEY (ID)
);
create unique index idx_1_COUNTER on T1 (POINTS);
	
CREATE TABLE T2 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	UNAME VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID)
);
create unique index idx_2_COUNTER on T2 (UNAME,POINTS);

CREATE TABLE T3 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	TEL INTEGER NOT NULL,
	PRIMARY KEY (ID)
);
create unique index idx_3_COUNTER on T3 (TEL,POINTS);

CREATE TABLE T4 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	UNAME VARCHAR(10) NOT NULL,
	SEX TINYINT NOT NULL,
	PRIMARY KEY (ID)
);
create unique index idx_4_COUNTER on T4 (UNAME,SEX,POINTS);