CREATE TABLE TU1 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	PRIMARY KEY (ID)
);
create unique index idx_U1_TREE on TU1 (POINTS);
	
CREATE TABLE TU2 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	UNAME VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID)
);
create unique index idx_U2_TREE on TU2 (UNAME,POINTS);

CREATE TABLE TU3 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	TEL INTEGER NOT NULL,
	PRIMARY KEY (ID)
);
create unique index idx_U3_TREE on TU3 (TEL,POINTS);

CREATE TABLE TU4 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	UNAME VARCHAR(10) NOT NULL,
	SEX TINYINT NOT NULL,
	PRIMARY KEY (ID)
);
create unique index idx_U4_TREE on TU4 (UNAME,SEX,POINTS);


CREATE TABLE TM1 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	PRIMARY KEY (ID)
);
create index idx_M1_TREE on TM1 (POINTS);
	
CREATE TABLE TM2 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	UNAME VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID)
);
create index idx_M2_TREE on TM2 (UNAME,POINTS);

CREATE TABLE TM3 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	TEL INTEGER NOT NULL,
	PRIMARY KEY (ID)
);
create index idx_M3_TREE on TM3 (TEL,POINTS);

CREATE TABLE TM4 (
	ID INTEGER NOT NULL,
	POINTS INTEGER NOT NULL,
	UNAME VARCHAR(10) NOT NULL,
	SEX TINYINT NOT NULL,
	PRIMARY KEY (ID)
);
create index idx_M4_TREE on TM4 (UNAME,SEX,POINTS);

CREATE TABLE P1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(300),
  NUM INTEGER NOT NULL,
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX P1_IDX_NUM_TREE ON P1 (NUM);

CREATE TABLE P2 (
    P2_ID INTEGER DEFAULT '0' NOT NULL,
    P2_DESC VARCHAR(300),
    P2_NUM1 INTEGER NOT NULL,
    P2_NUM2 INTEGER NOT NULL,
    PRIMARY KEY (P2_ID)
);
CREATE INDEX P2_IDX_P2NUM_TREE ON P2 (P2_NUM1,P2_NUM2);

CREATE TABLE P3 (
  P3_ID INTEGER DEFAULT '0' NOT NULL,
  P3_DESC VARCHAR(300),
  P3_NUM1 INTEGER NOT NULL,
  P3_NUM2 INTEGER NOT NULL,
  PRIMARY KEY (P3_ID)
);
---CREATE INDEX P3_IDX_P3NUM_TREE ON P2 (P3_NUM1,P3_NUM2);