CREATE TABLE P1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(300),
  CASH DECIMAL,
  NUM INTEGER,
  RATIO FLOAT,
  PRIMARY KEY (ID)
);

CREATE TABLE R1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(300),
  CASH DECIMAL,
  NUM INTEGER,
  RATIO FLOAT,
  PRIMARY KEY (ID)
);

CREATE TABLE P2 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(300),
  CASH DECIMAL,
  NUM INTEGER,
  RATIO FLOAT,
  CONSTRAINT P2_PK_TREE PRIMARY KEY (ID)
);

CREATE TABLE R2 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(300),
  CASH DECIMAL,
  NUM INTEGER,
  RATIO FLOAT,
  CONSTRAINT R2_PK_TREE PRIMARY KEY (ID)
);

CREATE TABLE ENG3465 (
  EMPNUM   VARCHAR(3) NOT NULL,
  PNUM     VARCHAR(3) NOT NULL,
  HOURS    DECIMAL(5),
  UNIQUE(EMPNUM,PNUM)
);