CREATE TABLE CATEGORY (
  CATID TINYINT DEFAULT '0' NOT NULL,
  CATNAME VARCHAR(16) DEFAULT NULL,
  CATDESCRIPTION VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (CATID)
);

CREATE TABLE ITEM (
  ITEMID INTEGER DEFAULT '0' NOT NULL,
  ITEMNAME VARCHAR(128) DEFAULT NULL,
  ITEMDESCRIPTION VARCHAR(128) DEFAULT NULL,
  SELLERID INTEGER DEFAULT '0' NOT NULL,
  CATEGORYID TINYINT DEFAULT '0' NOT NULL,
  HIGHBIDID INTEGER DEFAULT NULL,
  STARTPRICE FLOAT DEFAULT NULL,
  STARTTIME TIMESTAMP DEFAULT NULL,
  ENDTIME TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (ITEMID)
);

CREATE TABLE USER (
  USERID INTEGER DEFAULT '0' NOT NULL,
  LASTNAME VARCHAR(32) DEFAULT NULL,
  FIRSTNAME VARCHAR(32) DEFAULT NULL,
  STREETADDRESS VARCHAR(32) DEFAULT NULL,
  CITY VARCHAR(16) DEFAULT NULL,
  STATE VARCHAR(2) DEFAULT NULL,
  ZIP VARCHAR(16) DEFAULT NULL,
  EMAIL VARCHAR(32) DEFAULT NULL,
  PRIMARY KEY (USERID)
);

CREATE TABLE BID (
  BIDID INTEGER DEFAULT '0' NOT NULL,
  ITEMID INTEGER DEFAULT '0' NOT NULL,
  BIDDERID INTEGER DEFAULT '0' NOT NULL,
  BIDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  BIDPRICE FLOAT DEFAULT NULL,
  PRIMARY KEY (BIDID)
);

CREATE TABLE ITEM_EXPORT (
  ITEMID INTEGER DEFAULT '0' NOT NULL,
  ITEMNAME VARCHAR(128) DEFAULT NULL,
  ITEMDESCRIPTION VARCHAR(128) DEFAULT NULL,
  SELLERID INTEGER DEFAULT '0' NOT NULL,
  CATEGORYID TINYINT DEFAULT '0' NOT NULL,
  HIGHBIDID INTEGER DEFAULT NULL,
  STARTPRICE FLOAT DEFAULT NULL,
  STARTTIME TIMESTAMP DEFAULT NULL,
  ENDTIME TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (ITEMID)
);

CREATE TABLE BID_EXPORT (
  BIDID INTEGER DEFAULT '0' NOT NULL,
  ITEMID INTEGER DEFAULT '0' NOT NULL,
  BIDDERID INTEGER DEFAULT '0' NOT NULL,
  BIDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  BIDPRICE FLOAT DEFAULT NULL,
  PRIMARY KEY (BIDID)
);