CREATE TABLE SERVER_TMO_TEST (name varchar(32) NOT NULL);
PARTITION TABLE SERVER_TMO_TEST ON COLUMN name;

CREATE PROCEDURE PARTITION ON TABLE SERVER_TMO_TEST COLUMN name
FROM CLASS org.voltdb.client.ServerTimeoutTestProc;

