CREATE TABLE HELLOWORLD (
   HELLO VARCHAR(15),
   WORLD VARCHAR(15),
   DIALECT VARCHAR(15) NOT NULL,
   PRIMARY KEY (DIALECT)
);

CREATE TABLE USERACCOUNT (
   EMAIL VARCHAR(128) UNIQUE NOT NULL,
   FIRSTNAME VARCHAR(15),
   LASTNAME VARCHAR(15),
   LASTLOGIN TIMESTAMP,
   DIALECT VARCHAR(15) NOT NULL,
   PRIMARY KEY (EMAIL)
);

PARTITION TABLE USERACCOUNT ON COLUMN EMAIL;

CREATE PROCEDURE FROM CLASS Insert;
CREATE PROCEDURE FROM CLASS RegisterUser;
CREATE PROCEDURE FROM CLASS SignIn;

PARTITION PROCEDURE RegisterUser ON TABLE Useraccount COLUMN Email;
PARTITION PROCEDURE SignIn ON TABLE Useraccount COLUMN Email;

