CREATE TABLE HELLOWORLD (
   HELLO VARCHAR(15),
   WORLD VARCHAR(15),
   DIALECT VARCHAR(15) NOT NULL,
   PRIMARY KEY (DIALECT)
);

CREATE TABLE USERACCOUNT (
   EMAIL VARCHAR(128) UNIQUE NOT NULL,
   FIRSTNAME VARCHAR(15),
   LASTNAME VARCHAR(15),
   LASTLOGIN TIMESTAMP,
   DIALECT VARCHAR(15) NOT NULL,
   PRIMARY KEY (EMAIL)
);

PARTITION TABLE USERACCOUNT ON COLUMN EMAIL;

LOAD CLASSES helloworld.jar;

CREATE PROCEDURE FROM CLASS Insert;
CREATE PROCEDURE PARTITION ON TABLE Useraccount COLUMN Email FROM CLASS RegisterUser;
CREATE PROCEDURE PARTITION ON TABLE Useraccount COLUMN Email FROM CLASS SignIn;
