CREATE TABLE S (
    S_PK        BIGINT NOT NULL,
    V1          VARCHAR(500) ,
    TS1         TIMESTAMP,
    V2          VARCHAR(100),
    V3          VARCHAR(100),
    V4          VARCHAR(100),
    V5          VARCHAR(100),
    V6          VARCHAR(1) DEFAULT 'N',
    INT1        INTEGER,
    INT2        INTEGER,
    INT3        INTEGER,
    INT4        INTEGER,
    INT5        INTEGER,
    INT6        INTEGER,
    V7          VARCHAR(10),
    INT7        INTEGER,
    V8          VARCHAR(1) DEFAULT 'N',
    V9          VARCHAR(1) DEFAULT 'N',
    V10         VARCHAR(1) DEFAULT 'N',
    V11         VARCHAR(1) DEFAULT 'N',
    BIGINT1     BIGINT,
    V12         VARCHAR(16),
    BIGINT2     BIGINT,
    BIGINT3     BIGINT,
    DECIMAL1    DECIMAL(18,2),
    DECIMAL2    DECIMAL(18,2),
    DECIMAL3    DECIMAL(18,2),
    DECIMAL4    DECIMAL(18,2),
    BIGINT4     BIGINT,
    BIGINT5     BIGINT,
    V13         VARCHAR(20),
    BIGINT6     BIGINT,
    BIGINT7     BIGINT,
    BIGINT8     BIGINT,
    PRIMARY KEY(S_PK));

CREATE TABLE T (
    T_PK1       VARCHAR(32) NOT NULL,
    T_PK2       VARCHAR(32) NOT NULL,
    V1          VARCHAR(1) DEFAULT 'N',
    V2          VARCHAR(256),
    S_PK        BIGINT,
    V3          VARCHAR(32),
    V4          VARCHAR(20),
    V5          VARCHAR(100),
    V6          VARCHAR(50),
    V7          VARCHAR(500),
    V8          VARCHAR(1) DEFAULT 'N',
    V9          VARCHAR(256),
    V10         VARCHAR(256),
    V11         VARCHAR(256),
    V12         VARCHAR(100),
    V13         VARCHAR(50),
    V14         VARCHAR(25),
    V15         VARCHAR(50) DEFAULT 'US',
    TS1         TIMESTAMP,
    V16         VARCHAR(50),
    TS2         TIMESTAMP,
    V17         VARCHAR(50),
    V18         VARCHAR(32),
    V19         VARCHAR(1) DEFAULT 'N',
    V20         VARCHAR(25),
    V21         VARCHAR(50),
    V22         VARCHAR(50),
    V23         VARCHAR(1) DEFAULT 'N',
    V24         VARCHAR(32),
    BIGINT1     BIGINT,
    T_PK3       VARCHAR(120) NOT NULL,
    TS3         TIMESTAMP,
    V25         VARCHAR(32),
    TS4         TIMESTAMP,
    DECIMAL1    DECIMAL(10,2),
    V26         VARCHAR(10),
  --BIGINT2     BIGINT,
  --BIGINT3     BIGINT,
  --BIGINT4     BIGINT,
  --BIGINT5     BIGINT,
  --BIGINT6     BIGINT,
  --BIGINT7     BIGINT,
    V27         VARCHAR(1),
    BIGINT8     BIGINT,
    TS5         TIMESTAMP,
    V28         VARCHAR(150),
    V29         VARCHAR(50),
    V30         VARCHAR(5),
    V31         VARCHAR(100),
    V32         VARCHAR(50),
    INT1        INTEGER,
    CONSTRAINT T_PK_TREE PRIMARY KEY(T_PK1,T_PK2,T_PK3));
