CREATE TABLE BIG_TABLE (
    id BIGINT NOT NULL,
    s1 VARCHAR(60) DEFAULT '' NOT NULL,
    s2 VARCHAR(60) DEFAULT '' NOT NULL,
    s3 VARCHAR(60) DEFAULT '' NOT NULL,
    s4 VARCHAR(60) DEFAULT '' NOT NULL,
    s5 VARCHAR(60) DEFAULT '' NOT NULL,
    s6 VARCHAR(60) DEFAULT '' NOT NULL,
    s7 VARCHAR(60) DEFAULT '' NOT NULL,
    s8 VARCHAR(60) DEFAULT '' NOT NULL,
    CONSTRAINT NO_PK_TREE PRIMARY KEY (id)
);
