CREATE TABLE t4 (
    c1 VARCHAR(16) NOT NULL,
    c2 BIGINT DEFAULT 0 NOT NULL,
    c3 VARCHAR(36) DEFAULT '' NOT NULL
);

CREATE VIEW vt4(c1, c2, total)
    AS SELECT c1, c2, COUNT(*)
    FROM t4
    GROUP BY c1, c2;
