
FROM openjdk:8-jre-alpine

# bash is required by sqlcmd
RUN apk add --no-cache bash

ARG SERVERS=localhost
ARG WARMUP=5
ARG DURATION=120
ARG CHECKPOINT=50
ARG DELAY=1
ARG CLIENTVERSION=2
ARG PRIORITIZE=true
ARG SINGLECLIENT=true
ARG USESPS=true
ARG USEMPS=true
ARG ASYNC=true
ARG VERIFY=true
ARG VARIATION=5
ARG PRINTSTATS=true
ARG SPRATES="800,800,800,800,800,800,800,800"
ARG MPRATES="20,20,20,20,20,20,20,20"

# STANDARD ARGS
ARG LOG4J=""
ARG SSLFILE=""
ARG USERNAME=""
ARG PASSWORD=""
ARG STATSFILE=""
ARG DR=""
ARG SQLCMDPORT=""
# if set only load the DDL
ARG DDLONLY=""

ENV SERVERS=$SERVERS
ENV WARMUP=$WARMUP
ENV DURATION=$DURATION
ENV CHECKPOINT=$CHECKPOINT
ENV DELAY=$DELAY
ENV CLIENTVERSION=$CLIENTVERSION
ENV PRIORITIZE=$PRIORITIZE
ENV SINGLECLIENT=$SINGLECLIENT
ENV USESPS=$USESPS
ENV USEMPS=$USEMPS
ENV ASYNC=$ASYNC
ENV VERIFY=$VERIFY
ENV VARIATION=$VARIATION
ENV PRINTSTATS=$PRINTSTATS
ENV SPRATES="800,800,800,800,800,800,800,800"
ENV MPRATES="20,20,20,20,20,20,20,20"

ENV LOG4J=$LOG4J
ENV SSLFILE=$SSLFILE
ENV USERNAME=$USERNAME
ENV PASSWORD=$PASSWORD
ENV STATSFILE=$STATSFILE
ENV DR=$DR
ENV SQLCMDPORT=$SQLCMDPORT
ENV DDLONLY=$DDLONLY

# the voltdb directory should be built by the build_docker.sh script
COPY . /priority

WORKDIR /priority


CMD ./docker_run.sh
