
FROM openjdk:8-jre-alpine

# bash is required by sqlcmd
RUN apk add --no-cache bash

ARG SERVERS=localhost
ARG DISPLAYINTERVAL=5
ARG DURATION=120
ARG POOLSIZE=100000
ARG PRELOAD=true
ARG GETPUTRATIO=0.90
ARG KEYSIZE=32
ARG MINVALUESIZE=1024
ARG MAXVALUESIZE=1024
ARG USECOMPRESSION=false
ARG THREADS=40
ARG CSVFILE=periodic.csv.gz
ARG TOPOLOGYAWARE=true
ARG VJAR=""
ARG LOG4J=voltdb/log4j.xml
ARG SSLFILE=""
ARG USERNAME=""
ARG PASSWORD=""

ENV LOG4J=$LOG4J
ENV VJAR=$VJAR
ENV SERVERS=$SERVERS
ENV DISPLAYINTERVAL=$DISPLAYINTERVAL
ENV DURATION=$DURATION
ENV POOLSIZE=$POOLSIZE
ENV PRELOAD=$PRELOAD
ENV GETPUTRATIO=$GETPUTRATIO
ENV KEYSIZE=$KEYSIZE
ENV MINVALUESIZE=$MINVALUESIZE
ENV MAXVALUESIZE=$MAXVALUESIZE
ENV USECOMPRESSION=$USECOMPRESSION
ENV THREADS=$THREADS
ENV CSVFILE=$CSFILE
ENV TOPOLOGYAWARE=$TOPOLOGYAWARE
ENV SSLFILE=$SSLFILE
ENV USERNAME=$USERNAME
ENV PASSWORD=$PASSWORD

# the voltdb directory should be built by the build_docker.sh script
# COPY voltdb /kvbenchmark/voltdb
COPY . /kvbenchmark/

WORKDIR /kvbenchmark


CMD ./docker_run.sh
