--
-- The following stream is used to test basic export
--

-- Attribute for ea. supported type: nulls allowed
CREATE STREAM S_ALLOW_NULLS PARTITION ON COLUMN PKEY EXPORT TO TARGET S_ALLOW_NULLS (
 PKEY          INTEGER       NOT NULL,
 A_TINYINT     TINYINT,
 A_SMALLINT    SMALLINT,
 A_INTEGER     INTEGER,
 A_BIGINT      BIGINT,
 A_FLOAT       FLOAT,
 A_TIMESTAMP   TIMESTAMP,
 A_INLINE_S1   VARCHAR(4),
 A_INLINE_S2   VARCHAR(63),
 A_POOL_S      VARCHAR(65536),
 A_POOL_MAX_S  VARCHAR(1048576 BYTES),
 A_INLINE_B    VARBINARY(32),
 A_POOL_B      VARBINARY(256),
 A_DECIMAL     DECIMAL,
 A_GEOGRAPHY_POINT GEOGRAPHY_POINT,
 A_GEOGRAPHY   GEOGRAPHY,
);
