CREATE TABLE PEOPLE (PARTITION INTEGER NOT NULL, ID INTEGER, AGE INTEGER, SALARY FLOAT, CHILDREN INTEGER, PRIMARY KEY(ID));
CREATE VIEW MATPEOPLE (AGE, NUM, SALARIES, KIDS) AS SELECT AGE, COUNT(*), SUM(SALARY), SUM(CHILDREN) FROM PEOPLE WHERE AGE > 5 GROUP BY AGE;

CREATE TABLE THINGS (ID INTEGER, PRICE INTEGER, PRIMARY KEY(ID));
CREATE VIEW MATTHINGS (PRICE, NUM) AS SELECT PRICE, COUNT(*) FROM THINGS GROUP BY PRICE;

CREATE TABLE OVERFLOWTEST ( col_pk BIGINT NOT NULL, col_1 INTEGER NOT NULL, col_integer INTEGER, col_bigint BIGINT, PRIMARY KEY (COL_PK));

CREATE VIEW V_OVERFLOWTEST (col_1, num_rows, sum_integer, sum_bigint) AS SELECT col_1, count(*), sum(col_integer), sum(col_bigint) FROM overflowtest GROUP BY col_1; 
