CREATE TABLE PEOPLE (PARTITION INTEGER NOT NULL, ID INTEGER, AGE INTEGER, SALARY FLOAT, CHILDREN INTEGER, PRIMARY KEY(ID));
CREATE VIEW MATPEOPLE (AGE, NUM, SALARIES, KIDS) AS SELECT AGE, COUNT(*), SUM(SALARY), SUM(CHILDREN) FROM PEOPLE WHERE AGE > 5 GROUP BY AGE;

CREATE TABLE THINGS (ID INTEGER, PRICE INTEGER, PRIMARY KEY(ID));
CREATE VIEW MATTHINGS (PRICE, NUM) AS SELECT PRICE, COUNT(*) FROM THINGS GROUP BY PRICE;

CREATE TABLE OVERFLOWTEST ( col_pk BIGINT NOT NULL, col_1 INTEGER NOT NULL, col_integer INTEGER, col_bigint BIGINT, PRIMARY KEY (COL_PK));
CREATE VIEW V_OVERFLOWTEST (col_1, num_rows, sum_integer, sum_bigint) AS SELECT col_1, count(*), sum(col_integer), sum(col_bigint) FROM overflowtest GROUP BY col_1;


CREATE TABLE ENG798 (
    c1 VARCHAR(16) NOT NULL,
    c2 BIGINT DEFAULT 0 NOT NULL,
    c3 VARCHAR(36) DEFAULT '' NOT NULL,
    c4 VARCHAR(36),
    c5 TIMESTAMP,
    c6 TINYINT DEFAULT 0,
    c7 TIMESTAMP
);
CREATE VIEW V_ENG798(c1, c6, c2, c3, c4, c5, total)
    AS SELECT c1, c6, c2, c3, c4, c5, COUNT(*)
    FROM ENG798
    GROUP BY c1, c6, c2, c3, c4, c5;
