/* This file is part of VoltDB.
 * Copyright (C) 2008-2015 VoltDB Inc.
 *
 * This file contains original code and/or modifications of original code.
 * Any modifications made by VoltDB Inc. are licensed under the following
 * terms and conditions:
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. The ASF
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.voltdb.sqlparser.assertions.grammar;

import static java.lang.String.format;

import org.assertj.core.api.AbstractAssert;
import org.voltdb.sqlparser.syntax.grammar.Projection;

/**
 * {@link Projection} specific assertions - Generated by CustomAssertionGenerator.
 */
public class ProjectionAssert extends
        AbstractAssert<ProjectionAssert, Projection> {

    /**
     * Creates a new </code>{@link ProjectionAssert}</code> to make assertions on actual Projection.
     * @param actual the Projection we want to make assertions on.
     */
    public ProjectionAssert(Projection actual) {
        super(actual, ProjectionAssert.class);
    }

    /**
     * An entry point for ProjectionAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one's can write directly : <code>assertThat(myProjection)</code> and get specific assertion with code completion.
     * @param actual the Projection we want to make assertions on.
     * @return a new </code>{@link ProjectionAssert}</code>
     */
    public static ProjectionAssert assertThat(Projection actual) {
        return new ProjectionAssert(actual);
    }

    /**
     * Verifies that the actual Projection's alias is equal to the given one.
     * @param alias the given alias to compare the actual Projection's alias to.
     * @return this assertion object.
     * @throws AssertionError - if the actual Projection's alias is not equal to the given one.
     */
    public ProjectionAssert hasAlias(String alias) {
        // check that actual Projection we want to make assertions on is not null.
        isNotNull();

        // we overrides the default error message with a more explicit one
        String errorMessage = format(
                "\nExpected <%s> alias to be:\n  <%s>\n but was:\n  <%s>",
                actual, alias, actual.getAlias());

        // check
        if (!actual.getAlias().equals(alias)) {
            throw new AssertionError(errorMessage);
        }

        // return the current assertion for method chaining
        return this;
    }

    /**
     * Verifies that the actual Projection's columnName is equal to the given one.
     * @param columnName the given columnName to compare the actual Projection's columnName to.
     * @return this assertion object.
     * @throws AssertionError - if the actual Projection's columnName is not equal to the given one.
     */
    public ProjectionAssert hasColumnName(String columnName) {
        // check that actual Projection we want to make assertions on is not null.
        isNotNull();

        // we overrides the default error message with a more explicit one
        String errorMessage = format(
                "\nExpected <%s> columnName to be:\n  <%s>\n but was:\n  <%s>",
                actual, columnName, actual.getColumnName());

        // check
        if (!actual.getColumnName().equals(columnName)) {
            throw new AssertionError(errorMessage);
        }

        // return the current assertion for method chaining
        return this;
    }

    /**
     * Verifies that the actual Projection's tableName is equal to the given one.
     * @param tableName the given tableName to compare the actual Projection's tableName to.
     * @return this assertion object.
     * @throws AssertionError - if the actual Projection's tableName is not equal to the given one.
     */
    public ProjectionAssert hasTableName(String tableName) {
        // check that actual Projection we want to make assertions on is not null.
        isNotNull();

        // we overrides the default error message with a more explicit one
        String errorMessage = format(
                "\nExpected <%s> tableName to be:\n  <%s>\n but was:\n  <%s>",
                actual, tableName, actual.getTableName());

        // check
        if (!actual.getTableName().equals(tableName)) {
            throw new AssertionError(errorMessage);
        }

        // return the current assertion for method chaining
        return this;
    }

}
