/* This file is part of VoltDB.
 * Copyright (C) 2008-2015 VoltDB Inc.
 *
 * This file contains original code and/or modifications of original code.
 * Any modifications made by VoltDB Inc. are licensed under the following
 * terms and conditions:
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. The ASF
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package org.voltdb.sqlparser.assertions.grammar;

import static java.lang.String.format;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.Assertions;
import org.voltdb.sqlparser.semantics.grammar.SelectQuery;
import org.voltdb.sqlparser.syntax.grammar.Projection;

/**
 * {@link SelectQuery} specific assertions - Generated by CustomAssertionGenerator.
 */
public class SelectQueryAssert extends
        AbstractAssert<SelectQueryAssert, SelectQuery> {

    /**
     * Creates a new </code>{@link SelectQueryAssert}</code> to make assertions on actual SelectQuery.
     * @param actual the SelectQuery we want to make assertions on.
     */
    public SelectQueryAssert(SelectQuery actual) {
        super(actual, SelectQueryAssert.class);
    }

    /**
     * An entry point for SelectQueryAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one's can write directly : <code>assertThat(mySelectQuery)</code> and get specific assertion with code completion.
     * @param actual the SelectQuery we want to make assertions on.
     * @return a new </code>{@link SelectQueryAssert}</code>
     */
    public static SelectQueryAssert assertThat(SelectQuery actual) {
        return new SelectQueryAssert(actual);
    }

    /**
     * Verifies that the actual SelectQuery's projections contains the given Projection elements.
     * @param projections the given elements that should be contained in actual SelectQuery's projections.
     * @return this assertion object.
     * @throws AssertionError if the actual SelectQuery's projections does not contain all given Projection elements.
     */
    public SelectQueryAssert hasProjections(Projection... projections) {
        // check that actual SelectQuery we want to make assertions on is not null.
        isNotNull();

        // check that given Projection varargs is not null.
        if (projections == null)
            throw new AssertionError(
                    "Expecting projections parameter not to be null.");

        // check with standard error message (see commented below to set your own message).
        Assertions.assertThat(actual.getProjections()).contains(projections);

        // uncomment the 4 lines below if you want to build your own error message :
        // WritableAssertionInfo assertionInfo = new WritableAssertionInfo();
        // String errorMessage = "my error message";
        // assertionInfo.overridingErrorMessage(errorMessage);
        // Iterables.instance().assertContains(assertionInfo, actual.getTeamMates(), teamMates);

        // return the current assertion for method chaining
        return this;
    }

    /**
     * Verifies that the actual SelectQuery has no projections.
     * @return this assertion object.
     * @throws AssertionError if the actual SelectQuery's projections is not empty.
     */
    public SelectQueryAssert hasNoProjections() {
        // check that actual SelectQuery we want to make assertions on is not null.
        isNotNull();

        // we overrides the default error message with a more explicit one
        String errorMessage = format(
                "\nExpected :\n  <%s>\nnot to have projections but had :\n  <%s>",
                actual, actual.getProjections());

        // check
        if (!actual.getProjections().isEmpty())
            throw new AssertionError(errorMessage);

        // return the current assertion for method chaining
        return this;
    }

}
