#!/usr/bin/env bash

# This file is part of VoltDB.

# Copyright (C) 2008-2022 Volt Active Data Inc.
#
# This file contains original code and/or modifications of original code.
# Any modifications made by Volt Active Data Inc. are licensed under the following
# terms and conditions:
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Original license for parts of this script copied from or influenced by
# the Hadoop startup script:
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# The VoltDB Plan Checker Script

# resolve symlinks and canonicalize the path (make it absolute)
pushd . > /dev/null
this=$0
cd `dirname $this`
this=`basename $this`
while [ -L "$this" ]
do
    this=`readlink $this`
    cd `dirname $this`
    this=`basename $this`
done
this="$(pwd -P)/$this"
popd > /dev/null

# the root of the VoltDB installation
export VOLTDB_HOME=$(dirname $(dirname $(dirname "$this")))

VOLTDB_VOLTDB=$VOLTDB_HOME/voltdb
VOLTDB_LIB=$VOLTDB_HOME/lib

JAVA=`which java`

# some Java parameters
if [ "$JAVA_HOME" != "" ]; then
  JAVA=$JAVA_HOME/bin/java
fi
if [ "$JAVA" = "" ]; then
  echo "Couldn't find java version to run (make sure JAVA_HOME is set)."
  exit 1
fi

# add libs to CLASSPATH
for f in $VOLTDB_LIB/*.jar; do
    if $(echo $f | egrep -vq slf4j-log4j); then     # skip slf4j-log4j, since we are using slf4j-nop
        CLASSPATH+=:$f
    fi
done
# add test classes to CLASSPATH, make sure it works either release or debug build
# if we have both debug and release build, we will use the release one.
if [ -d $VOLTDB_HOME/obj/release/test ]; then
    build=release
elif [ -d $VOLTDB_HOME/obj/debug/test ]; then
    build=debug
else
    echo "Cannot find build directory $VOLTDB_HOME/obj/release/{prod,test} or $VOLTDB_HOME/obj/debug/{prod,test}"
    exit 1
fi

CLASSPATH+=:$VOLTDB_HOME/obj/$build/test:$VOLTDB_HOME/obj/$build/prod:$VOLTDB_HOME/third_party/java/jars/junit-4.12.jar

# check envvars to see if a user overrides log4j conf
# otherwise apply defaults
if [ -z "${LOG4J_CONFIG_PATH}" ]; then
  if [ -f "$VOLTDB_HOME/voltdb/utility-log4j.xml" ]; then
    LOG4J_CONFIG_PATH=$VOLTDB_HOME/voltdb/utility-log4j.xml
  elif [ -f "$VOLTDB_HOME/voltdb/log4j.xml" ]; then
    LOG4J_CONFIG_PATH=$VOLTDB_HOME/voltdb/log4j.xml
  else
    echo "Couldn't find log4j configuration file."
    exit 1
  fi
fi

exec $JAVA -Dlog4j.configuration=file://$LOG4J_CONFIG_PATH -classpath $CLASSPATH org.voltdb.plannerv2.PlanChecker "$@"
