
FROM openjdk:8-jre-alpine

# bash is required by sqlcmd
RUN apk add --no-cache bash


ARG USECLIENTV2="true"
ARG USEPRIORITIES="true"
ARG ENTROPY=127
ARG FILLERROWSIZE=10240
ARG REPLFILLERROWMB=32
ARG PARTFILLERROWMB=128
ARG PROGRESSTIMEOUT=20
ARG ALLOWINPROCADHOC=false
ARG DISABLEDTHREADS="Cappedlt"
ARG RATELIMIT=100000000
ARG MPRATIO=0.20
ARG SWAPRATIO=0.50
ARG UPSERTRATIO=0.50
ARG UPSERTHITRATIO=0.20
ARG ENABLEHASHMISMATCHGEN=false
ARG STATSFILE=""
ARG DR=""
ARG SQLCMDPORT=""
# if set only load the DDL
ARG DDLONLY=""


ARG SERVERS=localhost
ARG DISPLAYINTERVAL=5
ARG DURATION=120
ARG MINVALUESIZE=1024
ARG MAXVALUESIZE=1024
ARG USECOMPRESSION=false
ARG THREADS=40
ARG THREADOFFSET=0
ARG CSVFILE=periodic.csv.gz
ARG TOPOLOGYAWARE=true
ARG DROPTASKS=true
ARG VJAR=""
ARG LOG4J=""
ARG SSLFILE=""
ARG USERNAME=""
ARG PASSWORD=""

ENV LOG4J=$LOG4J
ENV VJAR=$VJAR
ENV SERVERS=$SERVERS
ENV DISPLAYINTERVAL=$DISPLAYINTERVAL
ENV DURATION=$DURATION
ENV MINVALUESIZE=$MINVALUESIZE
ENV MAXVALUESIZE=$MAXVALUESIZE
ENV USECOMPRESSION=$USECOMPRESSION
ENV THREADS=$THREADS
ENV CSVFILE=$CSFILE
ENV TOPOLOGYAWARE=$TOPOLOGYAWARE
ENV DROPTASKS=$DROPTASKS
ENV SSLFILE=$SSLFILE
ENV USERNAME=$USERNAME
ENV PASSWORD=$PASSWORD

ENV USECLIENTV2=$USECLIENTV2
ENV USEPRIORITIES=$USEPRIORITIES
ENV ENTROPY=$ENTROPY
ENV FILLERROWSIZE=$FILLERROWSIZE
ENV REPLFILLERROWMB=$REPLFILLERROWMB
ENV PARTFILLERROWMB=$PARTFILLERROWMB
ENV PROGRESSTIMEOUT=$PROGRESSTIMEOUT
ENV ALLOWINPROCADHOC=$ALLOWINPROCADHOC
ENV DISABLEDTHREADS=$DISABLEDTHREADS
ENV RATELIMIT=$RATELIMIT
ENV MPRATIO=$MPRATIO
ENV SWAPRATIO=$SWAPRATIO
ENV UPSERTRATIO=$UPSERTRATIO
ENV UPSERTHITRATIO=$UPSERTHITRATIO
ENV ENABLEHASHMISMATCHGEN=false
ENV STATSFILE=$STATSFILE
ENV DR=$DR
ENV SQLCMDPORT=$SQLCMDPORT
# if set only load the DDL
ENV DDLONLY=$DDLONLY

# the voltdb directory should be built by the build_docker.sh script
COPY . /txnid2/

WORKDIR /txnid2


CMD ./docker_run.sh
