#!/bin/bash

if [ "`ps aux | grep java | grep voter | grep -v grep | awk 'END {print NR}'`" != "0" ]; then
    kill `ps aux | grep java | grep voter | grep -v grep | awk '{print $2}'`
fi

if [ "`ps aux | grep java | grep voltkv | grep -v grep | awk 'END {print NR}'`" != "0" ]; then
    kill `ps aux | grep java | grep voltkv | grep -v grep | awk '{print $2}'`
fi

# if the system thinks it has an gnome-terminal in the path it's gnome linux
if [ ! -z `which gnome-terminal` ]; then
    # start the server
    gnome-terminal -e 'bash -c "cd '`dirname $0`'/../../examples/'$1';./run.sh;"' --geometry=120x10+0+0 --active
    # wait for voltdb to start (hack)
    sleep 7
    # start the client
    gnome-terminal -e 'bash -c "cd '`dirname $0`'/../../examples/'$1';./run.sh client;exec bash"' --geometry=120x10+0+150
    exit 0
fi

# if the system thinks it has an osascript in the path it's a mac
if [ ! -z `which osascript` ]; then
    # start the server
    osascript -e "tell app \"Terminal\" to do script \"bash -c \\\"cd '`dirname $0`'/../../examples/'$1';./run.sh;\\\"\""
    # wait for voltdb to start (hack)
    sleep 7
    # start the client
    osascript -e "tell app \"Terminal\" to do script \"bash -c \\\"cd '`dirname $0`'/../../examples/'$1';./run.sh client;exec bash\\\"\""
    exit 0
fi

# fallback
echo "We're sorry. This demo only supports Gnome's Terminal and OSX's Terminal.app."
exit -1
