/* This file is part of VoltDB.
 * Copyright (C) 2008-2015 VoltDB Inc.
 *
 * This file contains original code and/or modifications of original code.
 * Any modifications made by VoltDB Inc. are licensed under the following
 * terms and conditions:
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
/*
 * This file has been created by elves.  If you make changes to it,
 * the elves will become annoyed, will overwrite your changes with
 * whatever odd notions they have of what should
 * be here, and ignore your plaintive bleatings.  So, don't edit this file,
 * Unless you want your work to disappear.
 */
package org.voltdb.sqlparser;

import org.junit.Test;

import org.hsqldb_voltpatches.VoltXMLElement;
import org.hsqldb_voltpatches.HSQLInterface;
import org.voltdb.sqlparser.syntax.SQLKind;

import org.voltdb.sqlparser.assertions.semantics.VoltXMLElementAssert.IDTable;
import static org.voltdb.sqlparser.assertions.semantics.VoltXMLElementAssert.*;

public class TestArithmeticExpressions {
    HSQLInterface m_HSQLInterface = null;
    String        m_schema = null;
    public TestArithmeticExpressions() {
        m_HSQLInterface = HSQLInterface.loadHsqldb();
        String m_schema = "create table alpha ( id integer, beta integer, gamma integer );create table gamma ( id integer not null, zooba integer );create table fargle ( id integer not null, dooba integer )";
        try {
            m_HSQLInterface.processDDLStatementsUsingVoltSQLParser(m_schema, null);
        } catch (Exception ex) {
            System.err.printf("Error parsing ddl: %s\n", ex.getMessage());
        }
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestSum() throws Exception {
        String sql    = "select * from alpha where id + id = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "add",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "add"),
                                    withChildNamed(30, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(31, "alias", "ID"),
                                        withAttribute(32, "column", "ID"),
                                        withIdAttribute(33, idTable),
                                        withAttribute(34, "table", "ALPHA")),
                                    withChildNamed(35, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(36, "alias", "ID"),
                                        withAttribute(37, "column", "ID"),
                                        withIdAttribute(38, idTable),
                                        withAttribute(39, "table", "ALPHA"))),
                                withChildNamed(40, "value",
                                    withIdAttribute(41, idTable),
                                    withAttribute(42, "value", "0"),
                                    withAttribute(43, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestDiff() throws Exception {
        String sql    = "select * from alpha where id - id = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "subtract",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "subtract"),
                                    withChildNamed(30, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(31, "alias", "ID"),
                                        withAttribute(32, "column", "ID"),
                                        withIdAttribute(33, idTable),
                                        withAttribute(34, "table", "ALPHA")),
                                    withChildNamed(35, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(36, "alias", "ID"),
                                        withAttribute(37, "column", "ID"),
                                        withIdAttribute(38, idTable),
                                        withAttribute(39, "table", "ALPHA"))),
                                withChildNamed(40, "value",
                                    withIdAttribute(41, idTable),
                                    withAttribute(42, "value", "0"),
                                    withAttribute(43, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestProd() throws Exception {
        String sql    = "select * from alpha where id * id = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "multiply",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "multiply"),
                                    withChildNamed(30, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(31, "alias", "ID"),
                                        withAttribute(32, "column", "ID"),
                                        withIdAttribute(33, idTable),
                                        withAttribute(34, "table", "ALPHA")),
                                    withChildNamed(35, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(36, "alias", "ID"),
                                        withAttribute(37, "column", "ID"),
                                        withIdAttribute(38, idTable),
                                        withAttribute(39, "table", "ALPHA"))),
                                withChildNamed(40, "value",
                                    withIdAttribute(41, idTable),
                                    withAttribute(42, "value", "0"),
                                    withAttribute(43, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestDiv() throws Exception {
        String sql    = "select * from alpha where id / id = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "divide",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "divide"),
                                    withChildNamed(30, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(31, "alias", "ID"),
                                        withAttribute(32, "column", "ID"),
                                        withIdAttribute(33, idTable),
                                        withAttribute(34, "table", "ALPHA")),
                                    withChildNamed(35, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(36, "alias", "ID"),
                                        withAttribute(37, "column", "ID"),
                                        withIdAttribute(38, idTable),
                                        withAttribute(39, "table", "ALPHA"))),
                                withChildNamed(40, "value",
                                    withIdAttribute(41, idTable),
                                    withAttribute(42, "value", "0"),
                                    withAttribute(43, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestSumProd() throws Exception {
        String sql    = "select * from alpha where id + beta * gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "add",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "add"),
                                    withChildNamed(30, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(31, "alias", "ID"),
                                        withAttribute(32, "column", "ID"),
                                        withIdAttribute(33, idTable),
                                        withAttribute(34, "table", "ALPHA")),
                                    withChildNamed(35, "operation",
                                                   "optype", "multiply",
                                        withIdAttribute(36, idTable),
                                        withAttribute(37, "optype", "multiply"),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA")),
                                        withChildNamed(43, "columnref",
                                                       "alias", "GAMMA",
                                                       "column", "GAMMA",
                                                       "table", "ALPHA",
                                            withAttribute(44, "alias", "GAMMA"),
                                            withAttribute(45, "column", "GAMMA"),
                                            withIdAttribute(46, idTable),
                                            withAttribute(47, "table", "ALPHA")))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestProdSum() throws Exception {
        String sql    = "select * from alpha where id * beta + gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "add",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "add"),
                                    withChildNamed(30, "operation",
                                                   "optype", "multiply",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "multiply"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestSumDiv() throws Exception {
        String sql    = "select * from alpha where id + beta / gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "add",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "add"),
                                    withChildNamed(30, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(31, "alias", "ID"),
                                        withAttribute(32, "column", "ID"),
                                        withIdAttribute(33, idTable),
                                        withAttribute(34, "table", "ALPHA")),
                                    withChildNamed(35, "operation",
                                                   "optype", "divide",
                                        withIdAttribute(36, idTable),
                                        withAttribute(37, "optype", "divide"),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA")),
                                        withChildNamed(43, "columnref",
                                                       "alias", "GAMMA",
                                                       "column", "GAMMA",
                                                       "table", "ALPHA",
                                            withAttribute(44, "alias", "GAMMA"),
                                            withAttribute(45, "column", "GAMMA"),
                                            withIdAttribute(46, idTable),
                                            withAttribute(47, "table", "ALPHA")))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestDivSum() throws Exception {
        String sql    = "select * from alpha where id / beta + gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "add",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "add"),
                                    withChildNamed(30, "operation",
                                                   "optype", "divide",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "divide"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestDiffProd() throws Exception {
        String sql    = "select * from alpha where id - beta * gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "subtract",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "subtract"),
                                    withChildNamed(30, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(31, "alias", "ID"),
                                        withAttribute(32, "column", "ID"),
                                        withIdAttribute(33, idTable),
                                        withAttribute(34, "table", "ALPHA")),
                                    withChildNamed(35, "operation",
                                                   "optype", "multiply",
                                        withIdAttribute(36, idTable),
                                        withAttribute(37, "optype", "multiply"),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA")),
                                        withChildNamed(43, "columnref",
                                                       "alias", "GAMMA",
                                                       "column", "GAMMA",
                                                       "table", "ALPHA",
                                            withAttribute(44, "alias", "GAMMA"),
                                            withAttribute(45, "column", "GAMMA"),
                                            withIdAttribute(46, idTable),
                                            withAttribute(47, "table", "ALPHA")))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestProdDiff() throws Exception {
        String sql    = "select * from alpha where id * beta - gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "subtract",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "subtract"),
                                    withChildNamed(30, "operation",
                                                   "optype", "multiply",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "multiply"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestDiffDiv() throws Exception {
        String sql    = "select * from alpha where id - beta / gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "subtract",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "subtract"),
                                    withChildNamed(30, "columnref",
                                                   "alias", "ID",
                                                   "column", "ID",
                                                   "table", "ALPHA",
                                        withAttribute(31, "alias", "ID"),
                                        withAttribute(32, "column", "ID"),
                                        withIdAttribute(33, idTable),
                                        withAttribute(34, "table", "ALPHA")),
                                    withChildNamed(35, "operation",
                                                   "optype", "divide",
                                        withIdAttribute(36, idTable),
                                        withAttribute(37, "optype", "divide"),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA")),
                                        withChildNamed(43, "columnref",
                                                       "alias", "GAMMA",
                                                       "column", "GAMMA",
                                                       "table", "ALPHA",
                                            withAttribute(44, "alias", "GAMMA"),
                                            withAttribute(45, "column", "GAMMA"),
                                            withIdAttribute(46, idTable),
                                            withAttribute(47, "table", "ALPHA")))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestDivDiff() throws Exception {
        String sql    = "select * from alpha where id / beta - gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "subtract",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "subtract"),
                                    withChildNamed(30, "operation",
                                                   "optype", "divide",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "divide"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestSumDiff() throws Exception {
        String sql    = "select * from alpha where id + beta - gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "subtract",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "subtract"),
                                    withChildNamed(30, "operation",
                                                   "optype", "add",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "add"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestDiffSum() throws Exception {
        String sql    = "select * from alpha where id - beta + gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "add",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "add"),
                                    withChildNamed(30, "operation",
                                                   "optype", "subtract",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "subtract"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestProdDiv() throws Exception {
        String sql    = "select * from alpha where id * beta / gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "divide",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "divide"),
                                    withChildNamed(30, "operation",
                                                   "optype", "multiply",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "multiply"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestDivProd() throws Exception {
        String sql    = "select * from alpha where id / beta * gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "multiply",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "multiply"),
                                    withChildNamed(30, "operation",
                                                   "optype", "divide",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "divide"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestSumSum() throws Exception {
        String sql    = "select * from alpha where id + beta + gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "add",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "add"),
                                    withChildNamed(30, "operation",
                                                   "optype", "add",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "add"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestDiffDiff() throws Exception {
        String sql    = "select * from alpha where id - beta - gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "subtract",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "subtract"),
                                    withChildNamed(30, "operation",
                                                   "optype", "subtract",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "subtract"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestProdProd() throws Exception {
        String sql    = "select * from alpha where id * beta * gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "multiply",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "multiply"),
                                    withChildNamed(30, "operation",
                                                   "optype", "multiply",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "multiply"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }

    @SuppressWarnings("unchecked")
    @Test
    public void TestDivDiv() throws Exception {
        String sql    = "select * from alpha where id / beta / gamma = 0";
        IDTable idTable = new IDTable();
        VoltXMLElement element = m_HSQLInterface.getVoltXMLFromSQLUsingVoltSQLParser(sql, null, SQLKind.DQL);
        assertThat(element)
            .hasName(1, "select")
            .hasAllOf(
                withChildNamed(2, "columns",
                    withChildNamed(3, "columnref",
                                   "alias", "ID",
                                   "column", "ID",
                                   "table", "ALPHA",
                        withAttribute(4, "alias", "ID"),
                        withAttribute(5, "column", "ID"),
                        withIdAttribute(6, idTable),
                        withAttribute(7, "table", "ALPHA")),
                    withChildNamed(8, "columnref",
                                   "alias", "BETA",
                                   "column", "BETA",
                                   "table", "ALPHA",
                        withAttribute(9, "alias", "BETA"),
                        withAttribute(10, "column", "BETA"),
                        withIdAttribute(11, idTable),
                        withAttribute(12, "table", "ALPHA")),
                    withChildNamed(13, "columnref",
                                   "alias", "GAMMA",
                                   "column", "GAMMA",
                                   "table", "ALPHA",
                        withAttribute(14, "alias", "GAMMA"),
                        withAttribute(15, "column", "GAMMA"),
                        withIdAttribute(16, idTable),
                        withAttribute(17, "table", "ALPHA"))),
                withChildNamed(18, "parameters"),
                withChildNamed(19, "tablescans",
                    withChildNamed(20, "tablescan",
                        withAttribute(21, "jointype", "inner"),
                        withAttribute(22, "table", "ALPHA"),
                        withChildNamed(23, "joincond",
                            withChildNamed(24, "operation",
                                           "optype", "equal",
                                withIdAttribute(25, idTable),
                                withAttribute(26, "optype", "equal"),
                                withChildNamed(27, "operation",
                                               "optype", "divide",
                                    withIdAttribute(28, idTable),
                                    withAttribute(29, "optype", "divide"),
                                    withChildNamed(30, "operation",
                                                   "optype", "divide",
                                        withIdAttribute(31, idTable),
                                        withAttribute(32, "optype", "divide"),
                                        withChildNamed(33, "columnref",
                                                       "alias", "ID",
                                                       "column", "ID",
                                                       "table", "ALPHA",
                                            withAttribute(34, "alias", "ID"),
                                            withAttribute(35, "column", "ID"),
                                            withIdAttribute(36, idTable),
                                            withAttribute(37, "table", "ALPHA")),
                                        withChildNamed(38, "columnref",
                                                       "alias", "BETA",
                                                       "column", "BETA",
                                                       "table", "ALPHA",
                                            withAttribute(39, "alias", "BETA"),
                                            withAttribute(40, "column", "BETA"),
                                            withIdAttribute(41, idTable),
                                            withAttribute(42, "table", "ALPHA"))),
                                    withChildNamed(43, "columnref",
                                                   "alias", "GAMMA",
                                                   "column", "GAMMA",
                                                   "table", "ALPHA",
                                        withAttribute(44, "alias", "GAMMA"),
                                        withAttribute(45, "column", "GAMMA"),
                                        withIdAttribute(46, idTable),
                                        withAttribute(47, "table", "ALPHA"))),
                                withChildNamed(48, "value",
                                    withIdAttribute(49, idTable),
                                    withAttribute(50, "value", "0"),
                                    withAttribute(51, "valuetype", "INTEGER")))))));
    }
}
