CREATE TABLE nocapped (
id INTEGER NOT NULL, 
wage INTEGER not null,
dept INTEGER NOT NULL
);

CREATE TABLE capped0 (
id INTEGER NOT NULL, 
wage INTEGER not null,
dept INTEGER NOT NULL,
CONSTRAINT tblimit0 LIMIT PARTITION ROWS 0
);

CREATE TABLE capped2 (
id INTEGER NOT NULL, 
wage INTEGER not null,
dept INTEGER NOT NULL,
CONSTRAINT tblimit2 LIMIT PARTITION ROWS 2
);

CREATE TABLE capped3 (
id INTEGER NOT NULL, 
wage INTEGER not null,
dept INTEGER NOT NULL,
CONSTRAINT tblimit3 LIMIT PARTITION ROWS 3
);

CREATE TABLE RTABLE (
    ID INTEGER DEFAULT 0 NOT NULL,
    AGE INTEGER NOT NULL,
    WAGE FLOAT NOT NULL,
    NAME VARCHAR(32) DEFAULT NULL,
    CITY VARCHAR(300) DEFAULT NULL,
    CONSTRAINT PK_RTABLE PRIMARY KEY (ID)
);

CREATE INDEX RTABLE_INDEX_1 ON RTABLE (AGE);
CREATE INDEX RTABLE_INDEX_2 ON RTABLE (NAME);
CREATE INDEX RTABLE_INDEX_3 ON RTABLE (WAGE, substring(name, 0,1));

CREATE VIEW V_RTABLE (V_AGE, V_CITY, V_CNT, V_SUM_AGE, V_MIN_WAGE)
    AS SELECT AGE, CITY, COUNT(*), SUM(WAGE), MIN(WAGE)  
    FROM RTABLE  GROUP BY AGE, CITY;


CREATE TABLE PTABLE (
    ID INTEGER DEFAULT 0 NOT NULL,
    AGE INTEGER NOT NULL,
    WAGE FLOAT NOT NULL,
    NAME VARCHAR(32) DEFAULT NULL,
    CITY VARCHAR(300) DEFAULT NULL,
    CONSTRAINT PK_PTABLE PRIMARY KEY (ID)
);
PARTITION TABLE PTABLE ON COLUMN ID;

CREATE INDEX PTABLE_INDEX_1 ON PTABLE (AGE);
CREATE INDEX PTABLE_INDEX_2 ON PTABLE (NAME);
CREATE INDEX PTABLE_INDEX_3 ON PTABLE (WAGE, substring(name, 0,1));

CREATE VIEW V_PTABLE (V_AGE, V_CITY, V_CNT, V_SUM_AGE, V_MIN_WAGE)
    AS SELECT AGE, CITY, COUNT(*), SUM(WAGE), MIN(WAGE)  
    FROM PTABLE  GROUP BY AGE, CITY;