CREATE TABLE P1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  TINY TINYINT NOT NULL,
  SMALL SMALLINT NOT NULL,
  BIG BIGINT NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IP1 ON P1 (ID, TINY);
CREATE INDEX IP2 ON P1 (BIG, SMALL);
CREATE INDEX IP3 ON P1 (TINY);

CREATE TABLE R1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  TINY TINYINT NOT NULL,
  SMALL SMALLINT NOT NULL,
  BIG BIGINT NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IR1 ON R1 (TINY);