CREATE TABLE P1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  TINY TINYINT NOT NULL,
  SMALL SMALLINT NOT NULL,
  BIG BIGINT NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IP1 ON P1 (ID, TINY);
CREATE INDEX IP2 ON P1 (BIG, SMALL);
CREATE INDEX IP3 ON P1 (TINY);

CREATE TABLE R1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  TINY TINYINT NOT NULL,
  SMALL SMALLINT NOT NULL,
  BIG BIGINT NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IR1 ON R1 (TINY);

CREATE TABLE INDEXED_VL_TABLE1 (
  ID INTEGER DEFAULT 0 NOT NULL PRIMARY KEY,
  VC1 VARCHAR(3),
  VC2 VARCHAR(3 BYTES),
  VB1 VARBINARY(6)
);

CREATE TABLE INDEXED_VL_TABLE2 (
  ID INTEGER DEFAULT 0 NOT NULL PRIMARY KEY,
  VC1 VARCHAR(6),
  VC2 VARCHAR(6 BYTES),
  VB1 VARBINARY(12)
);
-- create index on varchar
CREATE INDEX VC1_INDEXED_VL1 ON INDEXED_VL_TABLE1 (VC1);
CREATE INDEX VC2_INDEXED_VL1 ON INDEXED_VL_TABLE1 (VC2);
CREATE INDEX VB1_INDEXED_VL1 ON INDEXED_VL_TABLE1 (VB1);

CREATE INDEX VC1_INDEXED_VL2 ON INDEXED_VL_TABLE2 (VC1);
CREATE INDEX VC2_INDEXED_VL2 ON INDEXED_VL_TABLE2 (VC2);
CREATE INDEX VB1_INDEXED_VL2 ON INDEXED_VL_TABLE2 (VB1);
