CREATE TABLE P1 (
  ID BIGINT NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE R1 (
  ID BIGINT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE P_TIME (    
ID INTEGER NOT NULL,
C1 INTEGER NOT NULL, 
T_NOW TIMESTAMP DEFAULT NOW,
T_CURRENT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
T1 TIMESTAMP DEFAULT NULL,
T2 TIMESTAMP DEFAULT NULL,
PRIMARY KEY (ID) );

PARTITION TABLE P_TIME ON COLUMN ID;