
FROM openjdk:8-jre-alpine

# bash is required by sqlcmd
RUN apk add --no-cache bash

ARG TOPIC=TEST_TOPIC
ARG SUBSCRIBE=true
ARG USEGROUPIDS=true
ARG SERVERS=localhost
ARG TOPICPORT=9092
ARG VARCHARSIZE=512
ARG ASCIIONLY=true
ARG USEAVRO=false
ARG USEKAFKA=false
ARG SCHEMAREGISTRY="http://localhost:8081"
ARG COUNT=5000
ARG PRODUCERS=1
ARG INSERTRATE=0
ARG INSERTWARNTHRESHOLD=90
ARG GROUPS=1
ARG GROUPMEMBERS=1
ARG STATICMEMBERS=false
ARG TRANSIENTMEMBERS=0
ARG TRANSIENTMAXDURATION=10
# TODO: randomize prefix
ARG GROUPPREFIX=test-prefix
ARG SESSIONTIMEOUT=30
ARG MAXPOLLSILENCE=120
ARG POLLPROGRESS=100
ARG VERIFICATION=ALL
ARG MAXFAILEDINSERTS=9223372036854775807
ARG LOGSUPPRESSION=10

ENV TOPIC=$TOPIC
ENV SUBSCRIBE=$SUBSCRIBE
ENV USEGROUPIDS=$USEGROUPIDS
ENV SERVERS=$SERVERS
ENV TOPICPORT=$TOPICPORT
ENV VARCHARSIZE=$VARCHARSIZE
ENV ASCIIONLY=$ASCIIONLY
ENV USEAVRO=$USEAVRO
ENV USEKAFKA=$USEKAFKA
ENV SCHEMAREGISTRY=$SCHEMAREGISTRY
ENV COUNT=$COUNT
ENV PRODUCERS=$PRODUCERS
ENV INSERTRATE=$INSERTRATE
ENV INSERTWARNTHRESHOLD=$INSERTWARNTHRESHOLD
ENV GROUPS=$GROUPS
ENV GROUPMEMBERS=$GROUPMEMBERS
ENV STATICMEMBERS=$STATICMEMBERS
ENV TRANSIENTMEMBERS=$TRANSIENTMEMBERS
ENV TRANSIENTMAXDURATION=$TRANSIENTMAXDURATION
ENV GROUPPREFIX=$GROUPPREFIX
ENV SESSIONTIMEOUT=$SESSIONTIMEOUT
ENV MAXPOLLSILENCE=$MAXPOLLSILENCE
ENV POLLPROGRESS=$POLLPROGRESS
ENV VERIFICATION=$VERIFICATION
ENV MAXFAILEDINSERTS=$MAXFAILEDINSERTS
ENV LOGSUPPRESSION=$LOGSUPPRESSION

# the voltdb directory should be built by the build_docker.sh script
# COPY voltdb /topicbenchmark2/voltdb
COPY . /topicbenchmark2/

WORKDIR /topicbenchmark2


CMD ./docker_run.sh
