CREATE TABLE SATELLITE (
  ID INTEGER DEFAULT '0' NOT NULL,
  MODEL_NUMBER VARCHAR(32),
  COUNTRY VARCHAR(10),
  SPEED FLOAT DEFAULT 0,
  DIRECTION FLOAT DEFAULT 0,
  LONGOFFSET FLOAT DEFAULT 0,
  LATOFFSET FLOAT DEFAULT 0,
  PRIMARY KEY (ID)
);
CREATE TABLE LOCATION (
  ID INTEGER DEFAULT '0' NOT NULL,
  LONGITUDE FLOAT DEFAULT 0,
  LATITUDE FLOAT DEFAULT 0,
  PRIMARY KEY (ID)
);
